/**
 * Curated lateral-thinking riddle bank for Tap Teasers.
 *
 * Each entry: a question, exactly four unique choices, the index of the
 * correct one, and an "aha" that teaches the lateral flip. Every riddle is
 * validated by `validateRiddle` in the test suite (well-formed + unique).
 *
 * >120 entries so the daily picker can serve 5 distinct riddles for years
 * without an obvious repeat.
 */

import type { Riddle } from "./engine";

export const RIDDLE_BANK: Riddle[] = [
  {
    question: "I can be cracked, made, told, and played. What am I?",
    choices: ["A code", "A joke", "A promise", "A record"],
    answerIndex: 1,
    aha: "A joke is cracked, made, told and played on someone — four verbs, one answer.",
  },
  {
    question: "The more of me you take, the more you leave behind. What am I?",
    choices: ["Memories", "Footsteps", "Time", "Breaths"],
    answerIndex: 1,
    aha: "Every footstep you take leaves one behind you — the classic flip of take vs leave.",
  },
  {
    question: "What gets bigger the more you take away from it?",
    choices: ["A debt", "A hole", "A shadow", "A secret"],
    answerIndex: 1,
    aha: "Remove more earth and the hole only grows — subtraction that adds.",
  },
  {
    question:
      "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?",
    choices: ["A ghost", "An echo", "A thought", "A flag"],
    answerIndex: 1,
    aha: "An echo answers you with no mouth and rides on moving air.",
  },
  {
    question: "What has many keys but opens no locks?",
    choices: ["A map", "A piano", "A river", "A keyring"],
    answerIndex: 1,
    aha: "A piano has dozens of keys and not one opens a lock — your brain loves category swaps.",
  },
  {
    question: "What has hands but cannot clap?",
    choices: ["A statue", "A clock", "A glove", "A tree"],
    answerIndex: 1,
    aha: "A clock's hands sweep the dial but never meet to clap.",
  },
  {
    question: "What has a neck but no head?",
    choices: ["A road", "A bottle", "A guitar pick", "A coin"],
    answerIndex: 1,
    aha: "A bottle's neck holds no head — body language taken literally.",
  },
  {
    question: "What can travel around the world while staying in a corner?",
    choices: ["A satellite", "A stamp", "A rumour", "A shadow"],
    answerIndex: 1,
    aha: "A stamp rides in the corner of an envelope all over the globe.",
  },
  {
    question: "What gets wetter the more it dries?",
    choices: ["A sponge", "A towel", "A cloud", "A river"],
    answerIndex: 1,
    aha: "A towel soaks up water as it dries you — it gets wetter by doing its job.",
  },
  {
    question: "What has a face and two hands but no arms or legs?",
    choices: ["A doll", "A clock", "A portrait", "A coin"],
    answerIndex: 1,
    aha: "A clock has a face and two hands and not a limb in sight.",
  },
  {
    question: "What can you catch but not throw?",
    choices: ["A ball", "A cold", "A glance", "A wave"],
    answerIndex: 1,
    aha: "You catch a cold, but no one ever throws one — idiom over physics.",
  },
  {
    question: "What has to be broken before you can use it?",
    choices: ["A code", "An egg", "A habit", "A record"],
    answerIndex: 1,
    aha: "You must break an egg to cook it — useful only once cracked.",
  },
  {
    question: "What has one eye but cannot see?",
    choices: ["A storm", "A needle", "A potato", "A camera"],
    answerIndex: 1,
    aha: "A needle's eye threads cloth but sees nothing at all.",
  },
  {
    question: "What goes up but never comes down?",
    choices: ["A balloon", "Your age", "Smoke", "A kite"],
    answerIndex: 1,
    aha: "Your age only climbs — there is no coming back down.",
  },
  {
    question: "What can fill a room but takes up no space?",
    choices: ["Air", "Light", "Dust", "Water"],
    answerIndex: 1,
    aha: "Light floods a room without occupying it — fills, but takes no space.",
  },
  {
    question: "What has cities but no houses, forests but no trees, and water but no fish?",
    choices: ["A dream", "A map", "A painting", "A model"],
    answerIndex: 1,
    aha: "A map shows all of these as symbols, never the real thing.",
  },
  {
    question: "What has a thumb and four fingers but is not alive?",
    choices: ["A statue", "A glove", "A robot", "A hand mirror"],
    answerIndex: 1,
    aha: "A glove has the shape of a hand without the life.",
  },
  {
    question: "What can run but never walks, has a bed but never sleeps?",
    choices: ["A clock", "A river", "A car", "A horse"],
    answerIndex: 1,
    aha: "A river runs along its bed yet neither walks nor sleeps.",
  },
  {
    question: "What kind of band never plays music?",
    choices: ["A jazz band", "A rubber band", "A brass band", "A marching band"],
    answerIndex: 1,
    aha: "A rubber band stretches but never makes a sound — the word band has two lives.",
  },
  {
    question: "What gets sharper the more you use it?",
    choices: ["A knife", "Your brain", "A pencil", "A blade"],
    answerIndex: 1,
    aha: "Tools dull with use, but the brain sharpens — the opposite of a blade.",
  },
  {
    question: "The person who makes it has no need of it. The person who buys it has no use for it. What is it?",
    choices: ["A gift", "A coffin", "A safe", "A clock"],
    answerIndex: 1,
    aha: "A coffin's maker won't use it and its buyer can't — the buyer buys it for someone else.",
  },
  {
    question: "What is so fragile that saying its name breaks it?",
    choices: ["Glass", "Silence", "A promise", "A bubble"],
    answerIndex: 1,
    aha: "Speak the word silence aloud and you have already destroyed it.",
  },
  {
    question: "What belongs to you but is used more by others?",
    choices: ["Your money", "Your name", "Your phone", "Your shadow"],
    answerIndex: 1,
    aha: "People say your name far more often than you do — yours, but used by others.",
  },
  {
    question: "What can you keep only after giving it to someone else?",
    choices: ["A gift", "Your word", "A secret", "A loan"],
    answerIndex: 1,
    aha: "You keep your word by giving it — the promise lives only once it is made.",
  },
  {
    question: "Where does today come before yesterday?",
    choices: ["In a mirror", "In a dictionary", "In a dream", "On a calendar"],
    answerIndex: 1,
    aha: "Alphabetically, today (t) lands before yesterday (y) in the dictionary.",
  },
  {
    question: "What word becomes shorter when you add two letters to it?",
    choices: ["Long", "Short", "Small", "Tiny"],
    answerIndex: 1,
    aha: "Add e-r to short and you get shorter — meaning meets spelling.",
  },
  {
    question: "What has 13 hearts but no other organs?",
    choices: ["A hospital", "A deck of cards", "A valentine", "A choir"],
    answerIndex: 1,
    aha: "A standard deck holds thirteen heart cards and not a single organ.",
  },
  {
    question: "What is full of holes but still holds water?",
    choices: ["A net", "A sponge", "A bucket", "A cloud"],
    answerIndex: 1,
    aha: "A sponge is riddled with holes yet soaks up and holds water.",
  },
  {
    question: "What invention lets you look right through a wall?",
    choices: ["A mirror", "A window", "A telescope", "An x-ray"],
    answerIndex: 1,
    aha: "A window is the everyday invention that lets you see straight through a wall.",
  },
  {
    question: "What can you serve but never eat?",
    choices: ["A meal", "A tennis ball", "A drink", "A guest"],
    answerIndex: 1,
    aha: "In tennis you serve the ball — a different kind of serving entirely.",
  },
  {
    question: "What has a ring but no finger?",
    choices: ["A bell", "A telephone", "A planet", "A tree"],
    answerIndex: 1,
    aha: "A telephone rings without ever wearing a ring — sound, not jewellery.",
  },
  {
    question: "What goes through towns and over hills but never moves?",
    choices: ["A river", "A road", "Wind", "A train"],
    answerIndex: 1,
    aha: "A road stretches across the land yet stays perfectly still.",
  },
  {
    question: "What has teeth but cannot bite?",
    choices: ["A shark", "A comb", "A trap", "A dog"],
    answerIndex: 1,
    aha: "A comb is all teeth and no bite.",
  },
  {
    question: "What building has the most stories?",
    choices: ["A skyscraper", "A library", "A courthouse", "A hotel"],
    answerIndex: 1,
    aha: "A library is packed with stories — the pun is on tales, not floors.",
  },
  {
    question: "What has words but never speaks?",
    choices: ["A parrot", "A book", "A radio", "A phone"],
    answerIndex: 1,
    aha: "A book is full of words yet utterly silent.",
  },
  {
    question: "What is always in front of you but cannot be seen?",
    choices: ["The wind", "The future", "The horizon", "Tomorrow's date"],
    answerIndex: 1,
    aha: "The future is forever ahead of you and never visible.",
  },
  {
    question: "What can be measured but has no length, width, or height?",
    choices: ["Distance", "Temperature", "Volume", "Speed"],
    answerIndex: 1,
    aha: "Temperature is measurable yet has no spatial dimension at all.",
  },
  {
    question: "What two things can you never eat for breakfast?",
    choices: ["Eggs and toast", "Lunch and dinner", "Cereal and milk", "Fruit and juice"],
    answerIndex: 1,
    aha: "Once it's breakfast you can't also be eating lunch or dinner — wordplay on meals.",
  },
  {
    question: "What loses its head in the morning but gets it back at night?",
    choices: ["A flower", "A pillow", "A clock", "A candle"],
    answerIndex: 1,
    aha: "A pillow is dented (loses its head) by day and plumped again at night.",
  },
  {
    question: "What can you break without touching it?",
    choices: ["A glass", "A promise", "A branch", "A window"],
    answerIndex: 1,
    aha: "A promise breaks through action, not contact — abstract over physical.",
  },
  {
    question: "What runs all around a yard yet never moves?",
    choices: ["A dog", "A fence", "A sprinkler", "A breeze"],
    answerIndex: 1,
    aha: "A fence runs the whole perimeter while standing perfectly still.",
  },
  {
    question: "What gets broken if it is not kept?",
    choices: ["A toy", "A promise", "A clock", "A window"],
    answerIndex: 1,
    aha: "A promise not kept is, by definition, broken.",
  },
  {
    question: "What kind of room has no doors or windows?",
    choices: ["A bathroom", "A mushroom", "A classroom", "A ballroom"],
    answerIndex: 1,
    aha: "A mushroom is a room only in spelling — no doors required.",
  },
  {
    question: "What flies without wings and cries without eyes?",
    choices: ["A bat", "A cloud", "A kite", "An angel"],
    answerIndex: 1,
    aha: "A cloud drifts wingless across the sky and 'cries' rain without eyes.",
  },
  {
    question: "What comes down but never goes up?",
    choices: ["A balloon", "Rain", "Smoke", "A rocket"],
    answerIndex: 1,
    aha: "Rain only falls — it never rises back to the sky as rain.",
  },
  {
    question: "What has a bottom at the top?",
    choices: ["A mountain", "Your legs", "A glass", "A ladder"],
    answerIndex: 1,
    aha: "Your legs end in your bottom, which sits at their top — anatomy as riddle.",
  },
  {
    question: "What is black when clean and white when dirty?",
    choices: ["A mirror", "A chalkboard", "A page", "A window"],
    answerIndex: 1,
    aha: "A clean chalkboard is black; covered in chalk it goes white — inverted logic.",
  },
  {
    question: "What can you hold without ever touching it?",
    choices: ["A handle", "Your breath", "A rope", "A thought"],
    answerIndex: 1,
    aha: "You hold your breath with no hands at all.",
  },
  {
    question: "What has many rings but no fingers?",
    choices: ["A jeweller", "A tree", "A bell tower", "A wedding"],
    answerIndex: 1,
    aha: "A tree records its age in rings, never wearing one.",
  },
  {
    question: "What gets bigger the more you feed it but dies if you give it water?",
    choices: ["A plant", "A fire", "A pet", "A balloon"],
    answerIndex: 1,
    aha: "Fire grows when fed fuel and dies the instant it's drenched.",
  },
  {
    question: "What can fly but has no wings, and can cry but has no eyes?",
    choices: ["A bird", "A cloud", "A plane", "An onion"],
    answerIndex: 1,
    aha: "A cloud floats wingless and weeps rain without eyes.",
  },
  {
    question: "What kind of coat is best put on wet?",
    choices: ["A raincoat", "A coat of paint", "A winter coat", "A lab coat"],
    answerIndex: 1,
    aha: "A coat of paint goes on wet by design — the word coat shifts meaning.",
  },
  {
    question: "What goes around the house but never moves an inch?",
    choices: ["The cat", "The wall", "The wind", "The mailman"],
    answerIndex: 1,
    aha: "A wall encircles the house and never budges.",
  },
  {
    question: "What is easy to get into but hard to get out of?",
    choices: ["A car", "Trouble", "A bed", "A coat"],
    answerIndex: 1,
    aha: "Trouble welcomes you in and resists letting you leave.",
  },
  {
    question: "What word is spelled wrong in every dictionary?",
    choices: ["Misspelled", "Wrong", "Error", "Incorrect"],
    answerIndex: 1,
    aha: "The word literally spelled w-r-o-n-g — the puzzle reads itself.",
  },
  {
    question: "What occurs once in a minute, twice in a moment, but never in a thousand years?",
    choices: ["A blink", "The letter M", "A heartbeat", "A second"],
    answerIndex: 1,
    aha: "The letter M sits once in minute, twice in moment, and not at all in thousand years.",
  },
  {
    question: "What begins with T, ends with T, and has T in it?",
    choices: ["A toaster", "A teapot", "A tablet", "A trumpet"],
    answerIndex: 1,
    aha: "A teapot begins and ends with T — and holds tea (T) inside.",
  },
  {
    question: "What has four wheels and flies?",
    choices: ["A race car", "A garbage truck", "A plane", "A skateboard"],
    answerIndex: 1,
    aha: "A garbage truck has wheels and attracts flies — the verb becomes a noun.",
  },
  {
    question: "What kind of tree can you carry in your hand?",
    choices: ["A bonsai", "A palm", "A sapling", "A bush"],
    answerIndex: 1,
    aha: "A palm tree shares its name with the palm of your hand.",
  },
  {
    question: "What can point in every direction but cannot reach its destination?",
    choices: ["A clock", "A signpost", "A weather vane", "A river"],
    answerIndex: 1,
    aha: "A signpost shows the way everywhere yet stays rooted, going nowhere.",
  },
  {
    question: "What has a head and a tail but no body?",
    choices: ["A snake", "A coin", "A comet", "A kite"],
    answerIndex: 1,
    aha: "A coin has heads and tails and nothing in between.",
  },
  {
    question: "What can you hear but never see, and only speaks when spoken to?",
    choices: ["A whisper", "An echo", "A thought", "The wind"],
    answerIndex: 1,
    aha: "An echo replies only after you call out, and you never see it.",
  },
  {
    question: "What kind of cup can't hold water?",
    choices: ["A paper cup", "A cupcake", "A teacup", "A measuring cup"],
    answerIndex: 1,
    aha: "A cupcake is a cake, not a vessel — the word cup is buried inside.",
  },
  {
    question: "What goes up and down but always stays in the same place?",
    choices: ["A yo-yo", "A staircase", "An elevator", "A swing"],
    answerIndex: 1,
    aha: "A staircase lets you go up and down while never moving itself.",
  },
  {
    question: "What can be opened but never closed?",
    choices: ["A door", "An egg", "A jar", "A book"],
    answerIndex: 1,
    aha: "Crack an egg open and there is no closing it again.",
  },
  {
    question: "What has branches but no leaves, trunk, or fruit?",
    choices: ["A river", "A bank", "A vine", "A path"],
    answerIndex: 1,
    aha: "A bank has branches — locations, not limbs.",
  },
  {
    question: "What can you pass to others while keeping it for yourself?",
    choices: ["A coin", "Knowledge", "A torch", "A baton"],
    answerIndex: 1,
    aha: "Teach what you know and you still keep it — knowledge multiplies when shared.",
  },
  {
    question: "What is harder to catch the faster you run?",
    choices: ["A bus", "Your breath", "A rival", "A train"],
    answerIndex: 1,
    aha: "Sprint and your breath grows harder to catch — speed works against you.",
  },
  {
    question: "What has a spine and tells stories but never speaks?",
    choices: ["A scholar", "A book", "A skeleton", "A poet"],
    answerIndex: 1,
    aha: "A book has a spine and is full of stories yet stays silent.",
  },
  {
    question: "What kind of ship has two mates but no captain?",
    choices: ["A pirate ship", "A relationship", "A cargo ship", "A sailboat"],
    answerIndex: 1,
    aha: "A relationship has mates and no captain — the suffix -ship is the trick.",
  },
  {
    question: "What gets passed around at parties but no one wants to keep?",
    choices: ["A gift", "A bad joke", "A plate", "A drink"],
    answerIndex: 1,
    aha: "Bad jokes circulate at parties and no one wants to hold onto them.",
  },
  {
    question: "What has legs but cannot walk?",
    choices: ["A spider", "A table", "A baby", "A clock"],
    answerIndex: 1,
    aha: "A table stands on legs that take it nowhere.",
  },
  {
    question: "What can you crack, make and tell, but is not a code?",
    choices: ["A safe", "A joke", "A whip", "A nut"],
    answerIndex: 1,
    aha: "You crack a joke, make a joke and tell a joke — three verbs converge.",
  },
  {
    question: "What flies all day but never leaves the ground?",
    choices: ["A bird", "A flag", "A balloon", "A drone"],
    answerIndex: 1,
    aha: "A flag flies in the breeze while tied firmly to its pole.",
  },
  {
    question: "What is taken before you can get it?",
    choices: ["A nap", "Your picture", "A breath", "A guess"],
    answerIndex: 1,
    aha: "Your picture must be taken before you can have it — taken to be given.",
  },
  {
    question: "What is always coming but never arrives?",
    choices: ["The mail", "Tomorrow", "A train", "The tide"],
    answerIndex: 1,
    aha: "Tomorrow is forever on its way and, by name, never here.",
  },
  {
    question: "What can be cracked and read but never written?",
    choices: ["A book", "A code", "A spine", "A scroll"],
    answerIndex: 1,
    aha: "You crack a code to read its hidden message — it's deciphered, not authored.",
  },
  {
    question: "What kind of dog never bites?",
    choices: ["A guard dog", "A hot dog", "A puppy", "A bulldog"],
    answerIndex: 1,
    aha: "A hot dog can be bitten but never bites back.",
  },
  {
    question: "What has a tongue but cannot taste?",
    choices: ["A snake", "A shoe", "A bell", "A frog"],
    answerIndex: 1,
    aha: "A shoe's tongue sits under the laces and tastes nothing.",
  },
  {
    question: "What word contains 26 letters but only has three syllables?",
    choices: ["Dictionary", "Alphabet", "Vocabulary", "Encyclopedia"],
    answerIndex: 1,
    aha: "The alphabet 'contains' all 26 letters — read it as a riddle, not a count.",
  },
  {
    question: "What goes in dry and comes out wet, the longer it's in the stronger it gets?",
    choices: ["A towel", "A tea bag", "A sponge", "A net"],
    answerIndex: 1,
    aha: "A tea bag steeps wetter and stronger the longer it sits.",
  },
  {
    question: "What kind of nut has no shell?",
    choices: ["A walnut", "A doughnut", "A peanut", "A hazelnut"],
    answerIndex: 1,
    aha: "A doughnut is a nut in name only — no shell, just sugar.",
  },
  {
    question: "What can you find at the end of a rainbow and the start of an emergency?",
    choices: ["Gold", "The letter E", "Hope", "Light"],
    answerIndex: 1,
    aha: "Rainbow ends with E and emergency begins with E — it's about letters, not pots of gold.",
  },
  {
    question: "What has a bark but no bite, and rings but no bell?",
    choices: ["A dog", "A tree", "A phone", "A clock"],
    answerIndex: 1,
    aha: "A tree has bark and growth rings — two everyday words turned literal.",
  },
  {
    question: "What kind of star is never seen in the night sky?",
    choices: ["A supernova", "A movie star", "A red giant", "A comet"],
    answerIndex: 1,
    aha: "A movie star shines on screen, never in the heavens.",
  },
  {
    question: "What word looks the same upside down and backwards?",
    choices: ["MOM", "SWIMS", "WOW", "NOON"],
    answerIndex: 1,
    aha: "SWIMS reads the same rotated 180 degrees — a true ambigram.",
  },
  {
    question: "What can you make that no one, not even you, can ever see?",
    choices: ["A wish", "A noise", "A plan", "A choice"],
    answerIndex: 1,
    aha: "You make a noise, but a sound is heard, never seen.",
  },
  {
    question: "What has many needles but does not sew?",
    choices: ["A tailor", "A pine tree", "A nurse", "A clock"],
    answerIndex: 1,
    aha: "A pine tree bristles with needles that never thread anything.",
  },
  {
    question: "What goes up when the rain comes down?",
    choices: ["A puddle", "An umbrella", "A river", "A cloud"],
    answerIndex: 1,
    aha: "When it rains, umbrellas go up everywhere — counter-motion.",
  },
  {
    question: "What gets shorter as it gets older?",
    choices: ["A road", "A candle", "A shadow", "A river"],
    answerIndex: 1,
    aha: "A burning candle loses height as time passes — aging by subtraction.",
  },
  {
    question: "What is yours but everyone else uses it more than you do?",
    choices: ["Your toothbrush", "Your name", "Your car", "Your house"],
    answerIndex: 1,
    aha: "Others say your name constantly; you rarely do — possession vs use.",
  },
  {
    question: "What kind of table has no legs and you can't eat at?",
    choices: ["A picnic table", "A timetable", "A coffee table", "A pool table"],
    answerIndex: 1,
    aha: "A timetable is a schedule, not furniture — the word table is hiding inside.",
  },
  {
    question: "What can hold the most weight while weighing almost nothing?",
    choices: ["A crane", "A balloon", "A bridge", "A shelf"],
    answerIndex: 1,
    aha: "A hot-air balloon lifts huge loads while being mostly air.",
  },
  {
    question: "What is at the end of everything?",
    choices: ["A period", "The letter G", "Silence", "Death"],
    answerIndex: 1,
    aha: "Everything ends with the letter G — the answer is in the spelling.",
  },
  {
    question: "What can you serve that always comes back to you?",
    choices: ["Dinner", "A boomerang", "A favour", "A tennis serve"],
    answerIndex: 1,
    aha: "A served boomerang loops right back — the literal return.",
  },
  {
    question: "What gets harder to grasp the tighter you hold it?",
    choices: ["A rope", "Sand", "A handle", "Water"],
    answerIndex: 1,
    aha: "Squeeze sand and it slips through your fingers — force defeats itself.",
  },
  {
    question: "What kind of band can never break?",
    choices: ["A rock band", "A waistband", "A brass band", "A wedding band"],
    answerIndex: 1,
    aha: "A waistband stretches but the riddle plays on bands that don't 'break up'.",
  },
  {
    question: "What flies forever and rests never?",
    choices: ["A bird", "Time", "The wind", "A comet"],
    answerIndex: 1,
    aha: "Time flies on without a single pause — the idiom made literal.",
  },
  {
    question: "What has roots that nobody sees, is taller than trees, up it goes, yet never grows?",
    choices: ["A tower", "A mountain", "A skyscraper", "A cloud"],
    answerIndex: 1,
    aha: "A mountain has deep roots, towers over forests, and never grows taller.",
  },
  {
    question: "What can be long or short, grown or bought, painted or left bare?",
    choices: ["Hair", "A nail", "A board", "A nose"],
    answerIndex: 1,
    aha: "A fingernail can be all of these — and a metal nail can be long, short, bought and painted too, but only the fingernail is also grown.",
  },
  {
    question: "What is always running but never gets tired?",
    choices: ["An athlete", "A refrigerator", "A river", "A clock"],
    answerIndex: 1,
    aha: "A refrigerator runs around the clock and never tires.",
  },
  {
    question: "What can be cold but never frozen, and hot but never burns?",
    choices: ["Coffee", "A trail", "Weather", "Soup"],
    answerIndex: 1,
    aha: "A trail can go cold or hot in the detective sense — temperature as metaphor.",
  },
  {
    question: "What kind of room can you never enter?",
    choices: ["A panic room", "Headroom", "A storeroom", "A dark room"],
    answerIndex: 1,
    aha: "Headroom is empty space above you, not a room you can walk into.",
  },
  {
    question: "What two words, added together, hold the most letters?",
    choices: ["Big book", "Post office", "Long list", "Full set"],
    answerIndex: 1,
    aha: "A post office holds the most letters — mail, not the alphabet.",
  },
  {
    question: "What runs but cannot walk, murmurs but cannot talk, has a bed but never sleeps?",
    choices: ["A clock", "A river", "A road", "A dream"],
    answerIndex: 1,
    aha: "A river runs, murmurs and has a bed — none of it human.",
  },
  {
    question: "What kind of cap can you never wear?",
    choices: ["A baseball cap", "A kneecap", "A swim cap", "A night cap"],
    answerIndex: 1,
    aha: "A kneecap is part of you, not headwear — the word cap is embedded.",
  },
  {
    question: "What goes around and around the wood but never goes into the wood?",
    choices: ["A saw", "Tree bark", "A vine", "A nail"],
    answerIndex: 1,
    aha: "Bark wraps around a tree's wood without ever entering it.",
  },
  {
    question: "What is made of water but if you put it in water it disappears?",
    choices: ["Steam", "Ice", "A wave", "A bubble"],
    answerIndex: 1,
    aha: "Ice is frozen water; drop it in water and it melts away.",
  },
  {
    question: "What can be heard and caught but never seen or thrown?",
    choices: ["A whisper", "A cold", "A song", "A wave"],
    answerIndex: 1,
    aha: "You hear that someone has a cold and you catch it — never seen, never thrown.",
  },
  {
    question: "What is light as a feather, yet the strongest person can't hold it for long?",
    choices: ["A balloon", "Your breath", "A whisper", "A snowflake"],
    answerIndex: 1,
    aha: "Hold your breath — weightless, yet impossible to hold for long.",
  },
  {
    question: "What kind of key is too big to carry in your pocket?",
    choices: ["A car key", "A monkey", "A house key", "A piano key"],
    answerIndex: 1,
    aha: "A monkey ends in -key — pocketing it is out of the question.",
  },
  {
    question: "What can be stolen, made, or taken, yet you keep it your whole life?",
    choices: ["A fortune", "A name", "A secret", "A title"],
    answerIndex: 1,
    aha: "Your name can be taken, made, or stolen, but it stays with you for life.",
  },
  {
    question: "What goes through glass without breaking it?",
    choices: ["A bullet", "Light", "A stone", "Sound"],
    answerIndex: 1,
    aha: "Light passes through glass leaving it whole.",
  },
  {
    question: "What can you break with a single word?",
    choices: ["A window", "Silence", "A bone", "A rule"],
    answerIndex: 1,
    aha: "One spoken word shatters silence instantly.",
  },
  {
    question: "What has many teeth but never visits a dentist?",
    choices: ["A shark", "A zipper", "A crocodile", "A baby"],
    answerIndex: 1,
    aha: "A zipper is a row of tiny teeth that never need cleaning.",
  },
  {
    question: "What kind of bow can't be tied?",
    choices: ["A hair bow", "A rainbow", "A shoe bow", "A gift bow"],
    answerIndex: 1,
    aha: "A rainbow arcs across the sky and can never be knotted.",
  },
  {
    question: "What has a mouth but never eats, a bank but holds no money?",
    choices: ["A cave", "A river", "A wallet", "A vault"],
    answerIndex: 1,
    aha: "A river has a mouth where it meets the sea and banks on either side.",
  },
  {
    question: "What gets passed from hand to hand yet is never held?",
    choices: ["A note", "Time", "A coin", "A baton"],
    answerIndex: 1,
    aha: "Time passes through every hand on a clock yet is never grasped.",
  },
  {
    question: "What kind of crown can't be worn on a head?",
    choices: ["A king's crown", "A tooth crown", "A flower crown", "A paper crown"],
    answerIndex: 1,
    aha: "A dental crown caps a tooth, not royalty.",
  },
  {
    question: "What can fill your mind but weighs nothing at all?",
    choices: ["A book", "An idea", "A worry", "A song"],
    answerIndex: 1,
    aha: "An idea can occupy your whole mind without any weight.",
  },
  {
    question: "What lets you walk on water without sinking?",
    choices: ["A boat", "Ice", "A raft", "A bridge"],
    answerIndex: 1,
    aha: "Frozen water — ice — turns the surface into solid ground.",
  },
  {
    question: "What is bought by the yard but worn by the foot?",
    choices: ["A scarf", "A carpet", "A ribbon", "A rope"],
    answerIndex: 1,
    aha: "Carpet is sold by the yard and walked on by the foot — two units, one trick.",
  },
  {
    question: "What can you catch in the dark but not see in the light?",
    choices: ["A firefly", "Sleep", "A cold", "A dream"],
    answerIndex: 1,
    aha: "You catch sleep in the dark; in daylight it slips away unseen.",
  },
  {
    question: "What follows you everywhere by day but vanishes at night?",
    choices: ["Your reflection", "Your shadow", "Your echo", "Your footprints"],
    answerIndex: 1,
    aha: "Your shadow trails you in sunlight and disappears in the dark.",
  },
  {
    question: "What kind of match can't start a fire?",
    choices: ["A safety match", "A football match", "A wax match", "A long match"],
    answerIndex: 1,
    aha: "A football match is a game, not a flame — same word, different world.",
  },
  {
    question: "What can be written, broken, given, and bound but is never an object?",
    choices: ["A letter", "A word", "A page", "A rule"],
    answerIndex: 1,
    aha: "Your word can be written down, broken, given and bound — yet it has no physical form.",
  },
  {
    question: "What has an end but no beginning, a home but no family, a space but no room?",
    choices: ["A book", "A keyboard", "A house", "A page"],
    answerIndex: 1,
    aha: "A keyboard has End, Home and Space keys — read the labels literally.",
  },
];
