/**
 * Curated lateral-thinking riddle bank for Tap Teasers.
 *
 * Each entry: a question, exactly four unique choices, the index of the
 * correct one, and an "aha" that teaches the lateral flip. Every riddle is
 * validated by `validateRiddle` in the test suite (well-formed + unique).
 *
 * >120 entries so the daily picker can serve 5 distinct riddles for years
 * without an obvious repeat.
 */

import type { Riddle } from "./engine";

export const RIDDLE_BANK: Riddle[] = [
  {
    question: "I can be cracked, made, told, and played. What am I?",
    choices: ["A code", "A joke", "A promise", "A record"],
    answerIndex: 1,
    aha: "A joke is cracked, made, told and played on someone — four verbs, one answer.",
  },
  {
    question: "The more of me you take, the more you leave behind. What am I?",
    choices: ["Memories", "Footsteps", "Time", "Breaths"],
    answerIndex: 1,
    aha: "Every footstep you take leaves one behind you — the classic flip of take vs leave.",
  },
  {
    question: "What gets bigger the more you take away from it?",
    choices: ["A debt", "A hole", "A shadow", "A secret"],
    answerIndex: 1,
    aha: "Remove more earth and the hole only grows — subtraction that adds.",
  },
  {
    question:
      "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?",
    choices: ["A ghost", "An echo", "A thought", "A flag"],
    answerIndex: 1,
    aha: "An echo answers you with no mouth and rides on moving air.",
  },
  {
    question: "What has many keys but opens no locks?",
    choices: ["A map", "A piano", "A river", "A keyring"],
    answerIndex: 1,
    aha: "A piano has dozens of keys and not one opens a lock — your brain loves category swaps.",
  },
  {
    question: "What has hands but cannot clap?",
    choices: ["A statue", "A clock", "A glove", "A tree"],
    answerIndex: 1,
    aha: "A clock's hands sweep the dial but never meet to clap.",
  },
  {
    question: "What has a neck but no head?",
    choices: ["A road", "A bottle", "A guitar pick", "A coin"],
    answerIndex: 1,
    aha: "A bottle's neck holds no head — body language taken literally.",
  },
  {
    question: "What can travel around the world while staying in a corner?",
    choices: ["A satellite", "A stamp", "A rumour", "A shadow"],
    answerIndex: 1,
    aha: "A stamp rides in the corner of an envelope all over the globe.",
  },
  {
    question: "What gets wetter the more it dries?",
    choices: ["A sponge", "A towel", "A cloud", "A river"],
    answerIndex: 1,
    aha: "A towel soaks up water as it dries you — it gets wetter by doing its job.",
  },
  {
    question: "What has a face and two hands but no arms or legs?",
    choices: ["A doll", "A clock", "A portrait", "A coin"],
    answerIndex: 1,
    aha: "A clock has a face and two hands and not a limb in sight.",
  },
  {
    question: "What can you catch but not throw?",
    choices: ["A ball", "A cold", "A glance", "A wave"],
    answerIndex: 1,
    aha: "You catch a cold, but no one ever throws one — idiom over physics.",
  },
  {
    question: "What has to be broken before you can use it?",
    choices: ["A code", "An egg", "A habit", "A record"],
    answerIndex: 1,
    aha: "You must break an egg to cook it — useful only once cracked.",
  },
  {
    question: "What has one eye but cannot see?",
    choices: ["A storm", "A needle", "A potato", "A camera"],
    answerIndex: 1,
    aha: "A needle's eye threads cloth but sees nothing at all.",
  },
  {
    question: "What goes up but never comes down?",
    choices: ["A balloon", "Your age", "Smoke", "A kite"],
    answerIndex: 1,
    aha: "Your age only climbs — there is no coming back down.",
  },
  {
    question: "What can fill a room but takes up no space?",
    choices: ["Air", "Light", "Dust", "Water"],
    answerIndex: 1,
    aha: "Light floods a room without occupying it — fills, but takes no space.",
  },
  {
    question: "What has cities but no houses, forests but no trees, and water but no fish?",
    choices: ["A dream", "A map", "A painting", "A model"],
    answerIndex: 1,
    aha: "A map shows all of these as symbols, never the real thing.",
  },
  {
    question: "What has a thumb and four fingers but is not alive?",
    choices: ["A statue", "A glove", "A robot", "A hand mirror"],
    answerIndex: 1,
    aha: "A glove has the shape of a hand without the life.",
  },
  {
    question: "What can run but never walks, has a bed but never sleeps?",
    choices: ["A clock", "A river", "A car", "A horse"],
    answerIndex: 1,
    aha: "A river runs along its bed yet neither walks nor sleeps.",
  },
  {
    question: "What kind of band never plays music?",
    choices: ["A jazz band", "A rubber band", "A brass band", "A marching band"],
    answerIndex: 1,
    aha: "A rubber band stretches but never makes a sound — the word band has two lives.",
  },
  {
    question: "What gets sharper the more you use it?",
    choices: ["A knife", "Your brain", "A pencil", "A blade"],
    answerIndex: 1,
    aha: "Tools dull with use, but the brain sharpens — the opposite of a blade.",
  },
  {
    question: "The person who makes it has no need of it. The person who buys it has no use for it. What is it?",
    choices: ["A gift", "A coffin", "A safe", "A clock"],
    answerIndex: 1,
    aha: "A coffin's maker won't use it and its buyer can't — the buyer buys it for someone else.",
  },
  {
    question: "What is so fragile that saying its name breaks it?",
    choices: ["Glass", "Silence", "A promise", "A bubble"],
    answerIndex: 1,
    aha: "Speak the word silence aloud and you have already destroyed it.",
  },
  {
    question: "What belongs to you but is used more by others?",
    choices: ["Your money", "Your name", "Your phone", "Your shadow"],
    answerIndex: 1,
    aha: "People say your name far more often than you do — yours, but used by others.",
  },
  {
    question: "What can you keep only after giving it to someone else?",
    choices: ["A gift", "Your word", "A secret", "A loan"],
    answerIndex: 1,
    aha: "You keep your word by giving it — the promise lives only once it is made.",
  },
  {
    question: "Where does today come before yesterday?",
    choices: ["In a mirror", "In a dictionary", "In a dream", "On a calendar"],
    answerIndex: 1,
    aha: "Alphabetically, today (t) lands before yesterday (y) in the dictionary.",
  },
  {
    question: "What word becomes shorter when you add two letters to it?",
    choices: ["Long", "Short", "Small", "Tiny"],
    answerIndex: 1,
    aha: "Add e-r to short and you get shorter — meaning meets spelling.",
  },
  {
    question: "What has 13 hearts but no other organs?",
    choices: ["A hospital", "A deck of cards", "A valentine", "A choir"],
    answerIndex: 1,
    aha: "A standard deck holds thirteen heart cards and not a single organ.",
  },
  {
    question: "What is full of holes but still holds water?",
    choices: ["A net", "A sponge", "A bucket", "A cloud"],
    answerIndex: 1,
    aha: "A sponge is riddled with holes yet soaks up and holds water.",
  },
  {
    question: "What invention lets you look right through a wall?",
    choices: ["A mirror", "A window", "A telescope", "An x-ray"],
    answerIndex: 1,
    aha: "A window is the everyday invention that lets you see straight through a wall.",
  },
  {
    question: "What can you serve but never eat?",
    choices: ["A meal", "A tennis ball", "A drink", "A guest"],
    answerIndex: 1,
    aha: "In tennis you serve the ball — a different kind of serving entirely.",
  },
  {
    question: "What has a ring but no finger?",
    choices: ["A bell", "A telephone", "A planet", "A tree"],
    answerIndex: 1,
    aha: "A telephone rings without ever wearing a ring — sound, not jewellery.",
  },
  {
    question: "What goes through towns and over hills but never moves?",
    choices: ["A river", "A road", "Wind", "A train"],
    answerIndex: 1,
    aha: "A road stretches across the land yet stays perfectly still.",
  },
  {
    question: "What has teeth but cannot bite?",
    choices: ["A shark", "A comb", "A trap", "A dog"],
    answerIndex: 1,
    aha: "A comb is all teeth and no bite.",
  },
  {
    question: "What building has the most stories?",
    choices: ["A skyscraper", "A library", "A courthouse", "A hotel"],
    answerIndex: 1,
    aha: "A library is packed with stories — the pun is on tales, not floors.",
  },
  {
    question: "What has words but never speaks?",
    choices: ["A parrot", "A book", "A radio", "A phone"],
    answerIndex: 1,
    aha: "A book is full of words yet utterly silent.",
  },
  {
    question: "What is always in front of you but cannot be seen?",
    choices: ["The wind", "The future", "The horizon", "Tomorrow's date"],
    answerIndex: 1,
    aha: "The future is forever ahead of you and never visible.",
  },
  {
    question: "What can be measured but has no length, width, or height?",
    choices: ["Distance", "Temperature", "Volume", "Speed"],
    answerIndex: 1,
    aha: "Temperature is measurable yet has no spatial dimension at all.",
  },
  {
    question: "What two things can you never eat for breakfast?",
    choices: ["Eggs and toast", "Lunch and dinner", "Cereal and milk", "Fruit and juice"],
    answerIndex: 1,
    aha: "Once it's breakfast you can't also be eating lunch or dinner — wordplay on meals.",
  },
  {
    question: "What loses its head in the morning but gets it back at night?",
    choices: ["A flower", "A pillow", "A clock", "A candle"],
    answerIndex: 1,
    aha: "A pillow is dented (loses its head) by day and plumped again at night.",
  },
  {
    question: "What can you break without touching it?",
    choices: ["A glass", "A promise", "A branch", "A window"],
    answerIndex: 1,
    aha: "A promise breaks through action, not contact — abstract over physical.",
  },
  {
    question: "What runs all around a yard yet never moves?",
    choices: ["A dog", "A fence", "A sprinkler", "A breeze"],
    answerIndex: 1,
    aha: "A fence runs the whole perimeter while standing perfectly still.",
  },
  {
    question: "What gets broken if it is not kept?",
    choices: ["A toy", "A promise", "A clock", "A window"],
    answerIndex: 1,
    aha: "A promise not kept is, by definition, broken.",
  },
  {
    question: "What kind of room has no doors or windows?",
    choices: ["A bathroom", "A mushroom", "A classroom", "A ballroom"],
    answerIndex: 1,
    aha: "A mushroom is a room only in spelling — no doors required.",
  },
  {
    question: "What flies without wings and cries without eyes?",
    choices: ["A bat", "A cloud", "A kite", "An angel"],
    answerIndex: 1,
    aha: "A cloud drifts wingless across the sky and 'cries' rain without eyes.",
  },
  {
    question: "What comes down but never goes up?",
    choices: ["A balloon", "Rain", "Smoke", "A rocket"],
    answerIndex: 1,
    aha: "Rain only falls — it never rises back to the sky as rain.",
  },
  {
    question: "What has a bottom at the top?",
    choices: ["A mountain", "Your legs", "A glass", "A ladder"],
    answerIndex: 1,
    aha: "Your legs end in your bottom, which sits at their top — anatomy as riddle.",
  },
  {
    question: "What is black when clean and white when dirty?",
    choices: ["A mirror", "A chalkboard", "A page", "A window"],
    answerIndex: 1,
    aha: "A clean chalkboard is black; covered in chalk it goes white — inverted logic.",
  },
  {
    question: "What can you hold without ever touching it?",
    choices: ["A handle", "Your breath", "A rope", "A thought"],
    answerIndex: 1,
    aha: "You hold your breath with no hands at all.",
  },
  {
    question: "What has many rings but no fingers?",
    choices: ["A jeweller", "A tree", "A bell tower", "A wedding"],
    answerIndex: 1,
    aha: "A tree records its age in rings, never wearing one.",
  },
  {
    question: "What gets bigger the more you feed it but dies if you give it water?",
    choices: ["A plant", "A fire", "A pet", "A balloon"],
    answerIndex: 1,
    aha: "Fire grows when fed fuel and dies the instant it's drenched.",
  },
  {
    question: "What can fly but has no wings, and can cry but has no eyes?",
    choices: ["A bird", "A cloud", "A plane", "An onion"],
    answerIndex: 1,
    aha: "A cloud floats wingless and weeps rain without eyes.",
  },
  {
    question: "What kind of coat is best put on wet?",
    choices: ["A raincoat", "A coat of paint", "A winter coat", "A lab coat"],
    answerIndex: 1,
    aha: "A coat of paint goes on wet by design — the word coat shifts meaning.",
  },
  {
    question: "What goes around the house but never moves an inch?",
    choices: ["The cat", "The wall", "The wind", "The mailman"],
    answerIndex: 1,
    aha: "A wall encircles the house and never budges.",
  },
  {
    question: "What is easy to get into but hard to get out of?",
    choices: ["A car", "Trouble", "A bed", "A coat"],
    answerIndex: 1,
    aha: "Trouble welcomes you in and resists letting you leave.",
  },
  {
    question: "What word is spelled wrong in every dictionary?",
    choices: ["Misspelled", "Wrong", "Error", "Incorrect"],
    answerIndex: 1,
    aha: "The word literally spelled w-r-o-n-g — the puzzle reads itself.",
  },
  {
    question: "What occurs once in a minute, twice in a moment, but never in a thousand years?",
    choices: ["A blink", "The letter M", "A heartbeat", "A second"],
    answerIndex: 1,
    aha: "The letter M sits once in minute, twice in moment, and not at all in thousand years.",
  },
  {
    question: "What begins with T, ends with T, and has T in it?",
    choices: ["A toaster", "A teapot", "A tablet", "A trumpet"],
    answerIndex: 1,
    aha: "A teapot begins and ends with T — and holds tea (T) inside.",
  },
  {
    question: "What has four wheels and flies?",
    choices: ["A race car", "A garbage truck", "A plane", "A skateboard"],
    answerIndex: 1,
    aha: "A garbage truck has wheels and attracts flies — the verb becomes a noun.",
  },
  {
    question: "What kind of tree can you carry in your hand?",
    choices: ["A bonsai", "A palm", "A sapling", "A bush"],
    answerIndex: 1,
    aha: "A palm tree shares its name with the palm of your hand.",
  },
  {
    question: "What can point in every direction but cannot reach its destination?",
    choices: ["A clock", "A signpost", "A weather vane", "A river"],
    answerIndex: 1,
    aha: "A signpost shows the way everywhere yet stays rooted, going nowhere.",
  },
  {
    question: "What has a head and a tail but no body?",
    choices: ["A snake", "A coin", "A comet", "A kite"],
    answerIndex: 1,
    aha: "A coin has heads and tails and nothing in between.",
  },
  {
    question: "What can you hear but never see, and only speaks when spoken to?",
    choices: ["A whisper", "An echo", "A thought", "The wind"],
    answerIndex: 1,
    aha: "An echo replies only after you call out, and you never see it.",
  },
  {
    question: "What kind of cup can't hold water?",
    choices: ["A paper cup", "A cupcake", "A teacup", "A measuring cup"],
    answerIndex: 1,
    aha: "A cupcake is a cake, not a vessel — the word cup is buried inside.",
  },
  {
    question: "What goes up and down but always stays in the same place?",
    choices: ["A yo-yo", "A staircase", "An elevator", "A swing"],
    answerIndex: 1,
    aha: "A staircase lets you go up and down while never moving itself.",
  },
  {
    question: "What can be opened but never closed?",
    choices: ["A door", "An egg", "A jar", "A book"],
    answerIndex: 1,
    aha: "Crack an egg open and there is no closing it again.",
  },
  {
    question: "What has branches but no leaves, trunk, or fruit?",
    choices: ["A river", "A bank", "A vine", "A path"],
    answerIndex: 1,
    aha: "A bank has branches — locations, not limbs.",
  },
  {
    question: "What can you pass to others while keeping it for yourself?",
    choices: ["A coin", "Knowledge", "A torch", "A baton"],
    answerIndex: 1,
    aha: "Teach what you know and you still keep it — knowledge multiplies when shared.",
  },
  {
    question: "What is harder to catch the faster you run?",
    choices: ["A bus", "Your breath", "A rival", "A train"],
    answerIndex: 1,
    aha: "Sprint and your breath grows harder to catch — speed works against you.",
  },
  {
    question: "What has a spine and tells stories but never speaks?",
    choices: ["A scholar", "A book", "A skeleton", "A poet"],
    answerIndex: 1,
    aha: "A book has a spine and is full of stories yet stays silent.",
  },
  {
    question: "What kind of ship has two mates but no captain?",
    choices: ["A pirate ship", "A relationship", "A cargo ship", "A sailboat"],
    answerIndex: 1,
    aha: "A relationship has mates and no captain — the suffix -ship is the trick.",
  },
  {
    question: "What gets passed around at parties but no one wants to keep?",
    choices: ["A gift", "A bad joke", "A plate", "A drink"],
    answerIndex: 1,
    aha: "Bad jokes circulate at parties and no one wants to hold onto them.",
  },
  {
    question: "What has legs but cannot walk?",
    choices: ["A spider", "A table", "A baby", "A clock"],
    answerIndex: 1,
    aha: "A table stands on legs that take it nowhere.",
  },
  {
    question: "What can you crack, make and tell, but is not a code?",
    choices: ["A safe", "A joke", "A whip", "A nut"],
    answerIndex: 1,
    aha: "You crack a joke, make a joke and tell a joke — three verbs converge.",
  },
  {
    question: "What flies all day but never leaves the ground?",
    choices: ["A bird", "A flag", "A balloon", "A drone"],
    answerIndex: 1,
    aha: "A flag flies in the breeze while tied firmly to its pole.",
  },
  {
    question: "What is taken before you can get it?",
    choices: ["A nap", "Your picture", "A breath", "A guess"],
    answerIndex: 1,
    aha: "Your picture must be taken before you can have it — taken to be given.",
  },
  {
    question: "What is always coming but never arrives?",
    choices: ["The mail", "Tomorrow", "A train", "The tide"],
    answerIndex: 1,
    aha: "Tomorrow is forever on its way and, by name, never here.",
  },
  {
    question: "What can be cracked and read but never written?",
    choices: ["A book", "A code", "A spine", "A scroll"],
    answerIndex: 1,
    aha: "You crack a code to read its hidden message — it's deciphered, not authored.",
  },
  {
    question: "What kind of dog never bites?",
    choices: ["A guard dog", "A hot dog", "A puppy", "A bulldog"],
    answerIndex: 1,
    aha: "A hot dog can be bitten but never bites back.",
  },
  {
    question: "What has a tongue but cannot taste?",
    choices: ["A snake", "A shoe", "A bell", "A frog"],
    answerIndex: 1,
    aha: "A shoe's tongue sits under the laces and tastes nothing.",
  },
  {
    question: "What word contains 26 letters but only has three syllables?",
    choices: ["Dictionary", "Alphabet", "Vocabulary", "Encyclopedia"],
    answerIndex: 1,
    aha: "The alphabet 'contains' all 26 letters — read it as a riddle, not a count.",
  },
  {
    question: "What goes in dry and comes out wet, the longer it's in the stronger it gets?",
    choices: ["A towel", "A tea bag", "A sponge", "A net"],
    answerIndex: 1,
    aha: "A tea bag steeps wetter and stronger the longer it sits.",
  },
  {
    question: "What kind of nut has no shell?",
    choices: ["A walnut", "A doughnut", "A peanut", "A hazelnut"],
    answerIndex: 1,
    aha: "A doughnut is a nut in name only — no shell, just sugar.",
  },
  {
    question: "What can you find at the end of a rainbow and the start of an emergency?",
    choices: ["Gold", "The letter E", "Hope", "Light"],
    answerIndex: 1,
    aha: "Rainbow ends with E and emergency begins with E — it's about letters, not pots of gold.",
  },
  {
    question: "What has a bark but no bite, and rings but no bell?",
    choices: ["A dog", "A tree", "A phone", "A clock"],
    answerIndex: 1,
    aha: "A tree has bark and growth rings — two everyday words turned literal.",
  },
  {
    question: "What kind of star is never seen in the night sky?",
    choices: ["A supernova", "A movie star", "A red giant", "A comet"],
    answerIndex: 1,
    aha: "A movie star shines on screen, never in the heavens.",
  },
  {
    question: "What word looks the same upside down and backwards?",
    choices: ["MOM", "SWIMS", "WOW", "NOON"],
    answerIndex: 1,
    aha: "SWIMS reads the same rotated 180 degrees — a true ambigram.",
  },
  {
    question: "What can you make that no one, not even you, can ever see?",
    choices: ["A wish", "A noise", "A plan", "A choice"],
    answerIndex: 1,
    aha: "You make a noise, but a sound is heard, never seen.",
  },
  {
    question: "What has many needles but does not sew?",
    choices: ["A tailor", "A pine tree", "A nurse", "A clock"],
    answerIndex: 1,
    aha: "A pine tree bristles with needles that never thread anything.",
  },
  {
    question: "What goes up when the rain comes down?",
    choices: ["A puddle", "An umbrella", "A river", "A cloud"],
    answerIndex: 1,
    aha: "When it rains, umbrellas go up everywhere — counter-motion.",
  },
  {
    question: "What gets shorter as it gets older?",
    choices: ["A road", "A candle", "A shadow", "A river"],
    answerIndex: 1,
    aha: "A burning candle loses height as time passes — aging by subtraction.",
  },
  {
    question: "What is yours but everyone else uses it more than you do?",
    choices: ["Your toothbrush", "Your name", "Your car", "Your house"],
    answerIndex: 1,
    aha: "Others say your name constantly; you rarely do — possession vs use.",
  },
  {
    question: "What kind of table has no legs and you can't eat at?",
    choices: ["A picnic table", "A timetable", "A coffee table", "A pool table"],
    answerIndex: 1,
    aha: "A timetable is a schedule, not furniture — the word table is hiding inside.",
  },
  {
    question: "What can hold the most weight while weighing almost nothing?",
    choices: ["A crane", "A balloon", "A bridge", "A shelf"],
    answerIndex: 1,
    aha: "A hot-air balloon lifts huge loads while being mostly air.",
  },
  {
    question: "What is at the end of everything?",
    choices: ["A period", "The letter G", "Silence", "Death"],
    answerIndex: 1,
    aha: "Everything ends with the letter G — the answer is in the spelling.",
  },
  {
    question: "What can you serve that always comes back to you?",
    choices: ["Dinner", "A boomerang", "A favour", "A tennis serve"],
    answerIndex: 1,
    aha: "A served boomerang loops right back — the literal return.",
  },
  {
    question: "What gets harder to grasp the tighter you hold it?",
    choices: ["A rope", "Sand", "A handle", "Water"],
    answerIndex: 1,
    aha: "Squeeze sand and it slips through your fingers — force defeats itself.",
  },
  {
    question: "What kind of band can never break?",
    choices: ["A rock band", "A waistband", "A brass band", "A wedding band"],
    answerIndex: 1,
    aha: "A waistband stretches but the riddle plays on bands that don't 'break up'.",
  },
  {
    question: "What flies forever and rests never?",
    choices: ["A bird", "Time", "The wind", "A comet"],
    answerIndex: 1,
    aha: "Time flies on without a single pause — the idiom made literal.",
  },
  {
    question: "What has roots that nobody sees, is taller than trees, up it goes, yet never grows?",
    choices: ["A tower", "A mountain", "A skyscraper", "A cloud"],
    answerIndex: 1,
    aha: "A mountain has deep roots, towers over forests, and never grows taller.",
  },
  {
    question: "What can be long or short, grown or bought, painted or left bare?",
    choices: ["Hair", "A nail", "A board", "A nose"],
    answerIndex: 1,
    aha: "A fingernail can be all of these — and a metal nail can be long, short, bought and painted too, but only the fingernail is also grown.",
  },
  {
    question: "What is always running but never gets tired?",
    choices: ["An athlete", "A refrigerator", "A river", "A clock"],
    answerIndex: 1,
    aha: "A refrigerator runs around the clock and never tires.",
  },
  {
    question: "What can be cold but never frozen, and hot but never burns?",
    choices: ["Coffee", "A trail", "Weather", "Soup"],
    answerIndex: 1,
    aha: "A trail can go cold or hot in the detective sense — temperature as metaphor.",
  },
  {
    question: "What kind of room can you never enter?",
    choices: ["A panic room", "Headroom", "A storeroom", "A dark room"],
    answerIndex: 1,
    aha: "Headroom is empty space above you, not a room you can walk into.",
  },
  {
    question: "What two words, added together, hold the most letters?",
    choices: ["Big book", "Post office", "Long list", "Full set"],
    answerIndex: 1,
    aha: "A post office holds the most letters — mail, not the alphabet.",
  },
  {
    question: "What runs but cannot walk, murmurs but cannot talk, has a bed but never sleeps?",
    choices: ["A clock", "A river", "A road", "A dream"],
    answerIndex: 1,
    aha: "A river runs, murmurs and has a bed — none of it human.",
  },
  {
    question: "What kind of cap can you never wear?",
    choices: ["A baseball cap", "A kneecap", "A swim cap", "A night cap"],
    answerIndex: 1,
    aha: "A kneecap is part of you, not headwear — the word cap is embedded.",
  },
  {
    question: "What goes around and around the wood but never goes into the wood?",
    choices: ["A saw", "Tree bark", "A vine", "A nail"],
    answerIndex: 1,
    aha: "Bark wraps around a tree's wood without ever entering it.",
  },
  {
    question: "What is made of water but if you put it in water it disappears?",
    choices: ["Steam", "Ice", "A wave", "A bubble"],
    answerIndex: 1,
    aha: "Ice is frozen water; drop it in water and it melts away.",
  },
  {
    question: "What can be heard and caught but never seen or thrown?",
    choices: ["A whisper", "A cold", "A song", "A wave"],
    answerIndex: 1,
    aha: "You hear that someone has a cold and you catch it — never seen, never thrown.",
  },
  {
    question: "What is light as a feather, yet the strongest person can't hold it for long?",
    choices: ["A balloon", "Your breath", "A whisper", "A snowflake"],
    answerIndex: 1,
    aha: "Hold your breath — weightless, yet impossible to hold for long.",
  },
  {
    question: "What kind of key is too big to carry in your pocket?",
    choices: ["A car key", "A monkey", "A house key", "A piano key"],
    answerIndex: 1,
    aha: "A monkey ends in -key — pocketing it is out of the question.",
  },
  {
    question: "What can be stolen, made, or taken, yet you keep it your whole life?",
    choices: ["A fortune", "A name", "A secret", "A title"],
    answerIndex: 1,
    aha: "Your name can be taken, made, or stolen, but it stays with you for life.",
  },
  {
    question: "What goes through glass without breaking it?",
    choices: ["A bullet", "Light", "A stone", "Sound"],
    answerIndex: 1,
    aha: "Light passes through glass leaving it whole.",
  },
  {
    question: "What can you break with a single word?",
    choices: ["A window", "Silence", "A bone", "A rule"],
    answerIndex: 1,
    aha: "One spoken word shatters silence instantly.",
  },
  {
    question: "What has many teeth but never visits a dentist?",
    choices: ["A shark", "A zipper", "A crocodile", "A baby"],
    answerIndex: 1,
    aha: "A zipper is a row of tiny teeth that never need cleaning.",
  },
  {
    question: "What kind of bow can't be tied?",
    choices: ["A hair bow", "A rainbow", "A shoe bow", "A gift bow"],
    answerIndex: 1,
    aha: "A rainbow arcs across the sky and can never be knotted.",
  },
  {
    question: "What has a mouth but never eats, a bank but holds no money?",
    choices: ["A cave", "A river", "A wallet", "A vault"],
    answerIndex: 1,
    aha: "A river has a mouth where it meets the sea and banks on either side.",
  },
  {
    question: "What gets passed from hand to hand yet is never held?",
    choices: ["A note", "Time", "A coin", "A baton"],
    answerIndex: 1,
    aha: "Time passes through every hand on a clock yet is never grasped.",
  },
  {
    question: "What kind of crown can't be worn on a head?",
    choices: ["A king's crown", "A tooth crown", "A flower crown", "A paper crown"],
    answerIndex: 1,
    aha: "A dental crown caps a tooth, not royalty.",
  },
  {
    question: "What can fill your mind but weighs nothing at all?",
    choices: ["A book", "An idea", "A worry", "A song"],
    answerIndex: 1,
    aha: "An idea can occupy your whole mind without any weight.",
  },
  {
    question: "What lets you walk on water without sinking?",
    choices: ["A boat", "Ice", "A raft", "A bridge"],
    answerIndex: 1,
    aha: "Frozen water — ice — turns the surface into solid ground.",
  },
  {
    question: "What is bought by the yard but worn by the foot?",
    choices: ["A scarf", "A carpet", "A ribbon", "A rope"],
    answerIndex: 1,
    aha: "Carpet is sold by the yard and walked on by the foot — two units, one trick.",
  },
  {
    question: "What can you catch in the dark but not see in the light?",
    choices: ["A firefly", "Sleep", "A cold", "A dream"],
    answerIndex: 1,
    aha: "You catch sleep in the dark; in daylight it slips away unseen.",
  },
  {
    question: "What follows you everywhere by day but vanishes at night?",
    choices: ["Your reflection", "Your shadow", "Your echo", "Your footprints"],
    answerIndex: 1,
    aha: "Your shadow trails you in sunlight and disappears in the dark.",
  },
  {
    question: "What kind of match can't start a fire?",
    choices: ["A safety match", "A football match", "A wax match", "A long match"],
    answerIndex: 1,
    aha: "A football match is a game, not a flame — same word, different world.",
  },
  {
    question: "What can be written, broken, given, and bound but is never an object?",
    choices: ["A letter", "A word", "A page", "A rule"],
    answerIndex: 1,
    aha: "Your word can be written down, broken, given and bound — yet it has no physical form.",
  },
  {
    question: "What has an end but no beginning, a home but no family, a space but no room?",
    choices: ["A book", "A keyboard", "A house", "A page"],
    answerIndex: 1,
    aha: "A keyboard has End, Home and Space keys — read the labels literally.",
  },
  {
    question: "What word starts and ends with the letter E but contains only one letter?",
    choices: ["Eve", "Envelope", "Edge", "Eagle"],
    answerIndex: 1,
    aha: "An envelope starts and ends with E and holds only one letter inside.",
  },
  {
    question: "What can travel the world without ever leaving its corner of a desk?",
    choices: ["A globe", "A postcard", "A pen", "A lamp"],
    answerIndex: 0,
    aha: "A globe shows the whole world while spinning in one spot on a desk.",
  },
  {
    question: "What kind of bank has no money but plenty of green?",
    choices: ["A piggy bank", "A river bank", "A blood bank", "A data bank"],
    answerIndex: 1,
    aha: "A river bank is lined with grass and reeds, never cash.",
  },
  {
    question: "What grows down while everything around it grows up?",
    choices: ["A root", "An icicle", "A vine", "A flower"],
    answerIndex: 1,
    aha: "An icicle extends downward as it builds, against the usual upward growth.",
  },
  {
    question: "What can you fill an empty bag with so it becomes lighter?",
    choices: ["Feathers", "Holes", "Air", "Nothing"],
    answerIndex: 1,
    aha: "Punch holes into the bag and it weighs even less than before.",
  },
  {
    question: "What kind of plate can you never serve food on?",
    choices: ["A dinner plate", "A license plate", "A dessert plate", "A side plate"],
    answerIndex: 1,
    aha: "A license plate names a car, not a meal.",
  },
  {
    question: "What loses its life in order to give light?",
    choices: ["A star", "A candle", "A lamp", "A torch"],
    answerIndex: 1,
    aha: "A candle burns itself away to keep the flame alive.",
  },
  {
    question: "What can you split in two yet still have a whole?",
    choices: ["A coin", "A banana", "An hour", "A team"],
    answerIndex: 2,
    aha: "Split an hour into two half-hours and you still have one whole hour.",
  },
  {
    question: "What kind of pen holds no ink but plenty of squeals?",
    choices: ["A fountain pen", "A pigpen", "A ballpoint pen", "A felt pen"],
    answerIndex: 1,
    aha: "A pigpen pens up pigs, not writing.",
  },
  {
    question: "What gets passed in school but holds no test answers?",
    choices: ["A note", "A grade", "A class", "A semester"],
    answerIndex: 2,
    aha: "You pass a class without it being a sheet of answers — passing as progress.",
  },
  {
    question: "What kind of watch tells no time at all?",
    choices: ["A wristwatch", "A night watch", "A pocket watch", "A stopwatch"],
    answerIndex: 1,
    aha: "A night watch is a period of guarding, not a timepiece.",
  },
  {
    question: "What can you draw without a pencil and shut without a door?",
    choices: ["A picture", "The curtains", "A breath", "A line"],
    answerIndex: 1,
    aha: "You draw the curtains and shut them — both verbs apply with no pencil or door.",
  },
  {
    question: "What has a sole but no soul, and a heel but never heals?",
    choices: ["A foot", "A shoe", "A sock", "A boot"],
    answerIndex: 1,
    aha: "A shoe has a sole and a heel, played against soul and heal.",
  },
  {
    question: "What word, when you remove the first letter, sounds exactly the same?",
    choices: ["Queue", "Apple", "Empty", "Knight"],
    answerIndex: 0,
    aha: "Drop the Q from queue and the leftover ueue still sounds like 'queue'.",
  },
  {
    question: "What kind of fly can you never swat?",
    choices: ["A horsefly", "A butterfly", "A dragonfly", "A firefly"],
    answerIndex: 1,
    aha: "A butterfly named for butter and flying is the gentle answer here, though the deeper joke is none of these is just a fly.",
  },
  {
    question: "What rises every morning without ever standing up?",
    choices: ["A flower", "Bread dough", "The sun", "Steam"],
    answerIndex: 2,
    aha: "The sun rises each morning with no legs to stand on.",
  },
  {
    question: "What can you lose that, once gone, you can never find again the same?",
    choices: ["Keys", "A moment", "A wallet", "A glove"],
    answerIndex: 1,
    aha: "A moment, once lost, is gone forever — unlike keys you can find again.",
  },
  {
    question: "What kind of bug never crawls and never flies?",
    choices: ["A ladybug", "A software bug", "A beetle", "A firefly"],
    answerIndex: 1,
    aha: "A software bug is a flaw in code, not a creature.",
  },
  {
    question: "What has a head of gold and a body of white and is loved on toast?",
    choices: ["An egg", "Butter", "Honey", "Cheese"],
    answerIndex: 0,
    aha: "A fried egg shows a golden yolk on a white body and crowns toast.",
  },
  {
    question: "What gets louder the quieter the room becomes?",
    choices: ["A whisper", "Silence", "A clock's tick", "Your heartbeat"],
    answerIndex: 2,
    aha: "A clock's tick seems to roar once everything else falls silent.",
  },
  {
    question: "What can you tie without a knot and break without a hand?",
    choices: ["A shoelace", "A score", "A rope", "A ribbon"],
    answerIndex: 1,
    aha: "You tie the score in a game and break a tie — no rope involved.",
  },
  {
    question: "What kind of jam can't be spread on bread?",
    choices: ["Strawberry jam", "A traffic jam", "Apricot jam", "Grape jam"],
    answerIndex: 1,
    aha: "A traffic jam clogs the road, not your toast.",
  },
  {
    question: "What goes all the way around a field yet plants nothing?",
    choices: ["A tractor", "A hedge", "A farmer", "The wind"],
    answerIndex: 1,
    aha: "A hedge borders a field completely without sowing a single seed.",
  },
  {
    question: "What can you swallow that may end up swallowing you?",
    choices: ["Water", "Pride", "Food", "Air"],
    answerIndex: 1,
    aha: "Swallow your pride, or let your pride swallow you — the metaphor cuts both ways.",
  },
  {
    question: "What kind of pool can't get you wet?",
    choices: ["A swimming pool", "A car pool", "A wading pool", "A lap pool"],
    answerIndex: 1,
    aha: "A car pool is shared driving, dry the whole way.",
  },
  {
    question: "What has four legs in the morning but is never an animal?",
    choices: ["A baby", "A table", "A dog", "A horse"],
    answerIndex: 1,
    aha: "A table stands on four legs all day and is no animal at all.",
  },
  {
    question: "What word is always pronounced wrong, even by experts?",
    choices: ["Wrong", "Difficult", "Misnomer", "Tricky"],
    answerIndex: 0,
    aha: "The word 'wrong' — the sentence is true the moment you say it.",
  },
  {
    question: "What kind of horn makes no sound at all?",
    choices: ["A car horn", "A shoehorn", "A trumpet", "A foghorn"],
    answerIndex: 1,
    aha: "A shoehorn helps your heel slide in silently.",
  },
  {
    question: "What can be high or low, flat or sharp, but is never touched?",
    choices: ["A wall", "A note", "A roof", "A blade"],
    answerIndex: 1,
    aha: "A musical note can be high, low, flat or sharp yet has no surface to touch.",
  },
  {
    question: "What grows shorter every time it speaks?",
    choices: ["A clock", "A candle wick", "A pencil", "A teacher"],
    answerIndex: 2,
    aha: "A pencil shortens with every word it writes — its 'speech' wears it down.",
  },
  {
    question: "What kind of star can you hold in your hand?",
    choices: ["A neutron star", "A starfish", "A pop star", "A shooting star"],
    answerIndex: 1,
    aha: "A starfish is a star you can lift from a tide pool.",
  },
  {
    question: "What stands still yet runs a marathon every single day?",
    choices: ["A statue", "A treadmill", "A tree", "A signpost"],
    answerIndex: 1,
    aha: "A treadmill's belt runs endlessly while the machine never moves.",
  },
  {
    question: "What can you spend, save, and waste, but never hold?",
    choices: ["Coins", "Time", "Notes", "Gold"],
    answerIndex: 1,
    aha: "Time can be spent, saved or wasted, yet it slips through your fingers.",
  },
  {
    question: "What kind of leaf never falls from a tree?",
    choices: ["A maple leaf", "A loose leaf", "An oak leaf", "A fig leaf"],
    answerIndex: 1,
    aha: "A loose-leaf page belongs to a binder, not a branch.",
  },
  {
    question: "What opens many doors yet has no hands?",
    choices: ["A guard", "A key", "A butler", "A breeze"],
    answerIndex: 1,
    aha: "A key opens door after door without a hand of its own.",
  },
  {
    question: "What can you hear coming but never going?",
    choices: ["A train", "Thunder", "Footsteps", "A bell"],
    answerIndex: 1,
    aha: "Thunder announces the storm's arrival; you never hear it depart.",
  },
  {
    question: "What kind of bowl can't hold soup?",
    choices: ["A salad bowl", "A Super Bowl", "A mixing bowl", "A fruit bowl"],
    answerIndex: 1,
    aha: "The Super Bowl is a game, not a dish.",
  },
  {
    question: "What can be deep or shallow, kept or broken, yet weighs nothing?",
    choices: ["A pool", "A promise", "A well", "A breath"],
    answerIndex: 1,
    aha: "A promise can run deep or shallow and be kept or broken, with no weight at all.",
  },
  {
    question: "What kind of nail can never be hammered?",
    choices: ["A finger nail", "A roofing nail", "A horseshoe nail", "A framing nail"],
    answerIndex: 0,
    aha: "Your fingernail would object strongly to a hammer.",
  },
  {
    question: "What sits in a corner yet sees the whole room?",
    choices: ["A lamp", "A camera", "A chair", "A plant"],
    answerIndex: 1,
    aha: "A security camera perches in a corner and watches everything.",
  },
  {
    question: "What kind of board can't you write on or stand on?",
    choices: ["A whiteboard", "A keyboard", "A surfboard", "A diving board"],
    answerIndex: 1,
    aha: "You type on a keyboard rather than chalk or surf it.",
  },
  {
    question: "What runs in your family but no one can outrun?",
    choices: ["A pet", "A trait", "A car", "A clock"],
    answerIndex: 1,
    aha: "A trait runs in the family — inherited, not raced.",
  },
  {
    question: "What is read the same whether you start from the left or the right?",
    choices: ["A poem", "A palindrome", "A headline", "A caption"],
    answerIndex: 1,
    aha: "A palindrome reads identically forwards and backwards.",
  },
  {
    question: "What can you fold but never crease, deal but never own?",
    choices: ["Paper", "Cards", "Laundry", "A map"],
    answerIndex: 1,
    aha: "In poker you fold your cards and deal them — neither folds the paper nor keeps them.",
  },
  {
    question: "What kind of trunk has no lid and no leaves?",
    choices: ["A car trunk", "An elephant trunk", "A tree trunk", "A storage trunk"],
    answerIndex: 1,
    aha: "An elephant's trunk is its nose, with no lid and no leaves.",
  },
  {
    question: "What goes up a chimney down but won't go down a chimney up?",
    choices: ["Smoke", "An umbrella", "A bird", "Soot"],
    answerIndex: 1,
    aha: "A closed (down) umbrella fits up a chimney, but open (up) it never will.",
  },
  {
    question: "What can be cast but never reeled in, and thrown but never caught?",
    choices: ["A line", "A vote", "A net", "A shadow"],
    answerIndex: 1,
    aha: "You cast a vote and throw your support — neither comes back to your hands.",
  },
  {
    question: "What kind of chest holds no treasure and beats all day?",
    choices: ["A toy chest", "Your chest", "A tool chest", "A war chest"],
    answerIndex: 1,
    aha: "Your chest houses a beating heart, not gold.",
  },
  {
    question: "What can climb mountains, cross rivers, and visit homes, all while flat on its back?",
    choices: ["A snail", "A road map", "A turtle", "A snake"],
    answerIndex: 1,
    aha: "A road map lies flat yet covers mountains, rivers and towns.",
  },
  {
    question: "What kind of tie can never be worn around your neck?",
    choices: ["A bow tie", "A tongue-tie", "A necktie", "A black tie"],
    answerIndex: 1,
    aha: "A tongue-tie is a stumble of speech, not an accessory.",
  },
  {
    question: "What kind of pitch has no music and no baseball?",
    choices: ["A perfect pitch", "A sales pitch", "A wild pitch", "A high pitch"],
    answerIndex: 1,
    aha: "A sales pitch is a persuasive speech, not a sound or a throw.",
  },
  {
    question: "What can you break with a whisper but never with a hammer?",
    choices: ["A rule", "Silence", "A spell", "Glass"],
    answerIndex: 1,
    aha: "The faintest whisper shatters silence, while a hammer cannot touch it.",
  },
  {
    question: "What has a bed of its own but is never tucked in?",
    choices: ["A child", "A flower bed", "A hotel", "A nurse"],
    answerIndex: 1,
    aha: "A flower bed is a patch of garden, never a place for sleep.",
  },
  {
    question: "What kind of light is heavy enough to crush you?",
    choices: ["Sunlight", "Limelight", "Spotlight", "A streetlight"],
    answerIndex: 3,
    aha: "A streetlight is a solid metal fixture, despite the word light.",
  },
  {
    question: "What kind of date can you never circle on a calendar?",
    choices: ["A birthday", "A date palm fruit", "An anniversary", "A deadline"],
    answerIndex: 1,
    aha: "A date is also a sweet fruit you eat, not a day to mark.",
  },
  {
    question: "What has a face that turns red but never feels shame?",
    choices: ["A clown", "A stoplight", "A tomato", "A sunset"],
    answerIndex: 1,
    aha: "A stoplight's face glows red on command, with no emotion involved.",
  },
  {
    question: "What kind of mouse is afraid of no cat?",
    choices: ["A field mouse", "A computer mouse", "A house mouse", "A baby mouse"],
    answerIndex: 1,
    aha: "A computer mouse clicks fearlessly, since it isn't really a rodent.",
  },
  {
    question: "What can you draw that fills the whole sky yet uses no ink?",
    choices: ["A cloud", "A conclusion", "A blank", "A breath"],
    answerIndex: 1,
    aha: "You draw a conclusion in your mind, no pen or paper required.",
  },
  {
    question: "What kind of bridge carries no traffic and spans no river?",
    choices: ["A drawbridge", "The bridge of your nose", "A footbridge", "A toll bridge"],
    answerIndex: 1,
    aha: "The bridge of your nose connects your eyes, carrying nothing across.",
  },
  {
    question: "What has scales but never weighs anything, and a tail but no fur?",
    choices: ["A lizard", "A fish on a menu", "A song", "A snake"],
    answerIndex: 2,
    aha: "A song has musical scales and a fading tail-off, yet no body at all.",
  },
  {
    question: "What can be left or right but is never a direction?",
    choices: ["A turn", "A leftover", "A hand", "A side"],
    answerIndex: 1,
    aha: "Food that's left over is what remains, playing on left vs right.",
  },
  {
    question: "What kind of fan never cools you down?",
    choices: ["A ceiling fan", "A sports fan", "A handheld fan", "An exhaust fan"],
    answerIndex: 1,
    aha: "A sports fan is an enthusiast, not a breeze-maker.",
  },
  {
    question: "What is full of keys yet cannot start a single car?",
    choices: ["A keyring", "A keyboard", "A locksmith", "A glovebox"],
    answerIndex: 1,
    aha: "A keyboard is crowded with keys that type rather than ignite.",
  },
  {
    question: "What can you crack with your knuckles but never with a nut?",
    choices: ["A code", "A joint", "An egg", "A whip"],
    answerIndex: 1,
    aha: "You crack a knuckle joint, a meaning of crack having nothing to do with nuts.",
  },
  {
    question: "What kind of court has no judge and no tennis?",
    choices: ["A supreme court", "A courtship", "A basketball court", "A food court"],
    answerIndex: 1,
    aha: "Courtship is the act of wooing someone, the word court hidden inside.",
  },
  {
    question: "What has a sole purpose to be stepped on?",
    choices: ["A doormat", "A shoe sole", "A staircase", "A floor"],
    answerIndex: 1,
    aha: "A shoe's sole exists to be stepped on, a pun on sole and only.",
  },
  {
    question: "What word is always written in capital letters, even in the middle of a sentence?",
    choices: ["Name", "I", "Country", "Day"],
    answerIndex: 1,
    aha: "The pronoun I is always capitalized wherever it appears in English.",
  },
  {
    question: "What kind of pole is too cold to climb?",
    choices: ["A flagpole", "The North Pole", "A fishing pole", "A telephone pole"],
    answerIndex: 1,
    aha: "The North Pole is a frozen point on the globe, not something you scale.",
  },
  {
    question: "What can be hot, sweet, or iced, yet is never a drink?",
    choices: ["Coffee", "A temper", "Tea", "Cocoa"],
    answerIndex: 1,
    aha: "A temper can be hot, and the phrasing tricks you toward beverages.",
  },
  {
    question: "What has a trunk packed for travel but no clothes inside?",
    choices: ["A suitcase", "A car", "A wardrobe", "A backpack"],
    answerIndex: 1,
    aha: "A car's trunk carries luggage and cargo, but the trunk itself holds no garments by default.",
  },
  {
    question: "What kind of wave will never reach the shore?",
    choices: ["A tidal wave", "A hand wave", "A heat wave", "A sound wave"],
    answerIndex: 1,
    aha: "A friendly hand wave is a gesture, not water rolling to the beach.",
  },
  {
    question: "What stands on one leg with its heart in its head?",
    choices: ["A flamingo", "A cabbage", "A scarecrow", "A mushroom"],
    answerIndex: 1,
    aha: "A cabbage grows on a single stalk and its dense core is called its heart.",
  },
  {
    question: "What kind of ring makes you late rather than married?",
    choices: ["A wedding ring", "An alarm's ring", "A boxing ring", "A key ring"],
    answerIndex: 1,
    aha: "An alarm's ring you ignore is what makes you late, not jewellery.",
  },
  {
    question: "What can you throw down but never pick up?",
    choices: ["A ball", "A challenge", "A coin", "A rope"],
    answerIndex: 1,
    aha: "You throw down a challenge, an act that cannot be physically retrieved.",
  },
  {
    question: "What kind of bar serves no drinks and locks no door?",
    choices: ["A crowbar", "A chocolate bar", "A sandbar", "A salad bar"],
    answerIndex: 1,
    aha: "A chocolate bar is a sweet treat, the word bar doing different work.",
  },
  {
    question: "What gets thrown at parties yet hurts no one?",
    choices: ["A punch", "A bash", "A toast", "Confetti"],
    answerIndex: 1,
    aha: "A bash is itself a party, so the party is thrown rather than an object.",
  },
  {
    question: "What kind of file can never be opened on a computer?",
    choices: ["A text file", "A nail file", "A zip file", "A backup file"],
    answerIndex: 1,
    aha: "A nail file smooths your nails and has nothing to do with software.",
  },
  {
    question: "What has a current but no plug, and a bank but no teller?",
    choices: ["A battery", "A river", "A circuit", "A wallet"],
    answerIndex: 1,
    aha: "A river has a flowing current and banks on each side, none electrical or financial.",
  },
  {
    question: "What kind of pound holds animals instead of money?",
    choices: ["A British pound", "A dog pound", "A pound of flour", "A pound sign"],
    answerIndex: 1,
    aha: "A dog pound is a shelter for strays, sharing only the word with currency.",
  },
  {
    question: "What can you blow yet never inflate?",
    choices: ["A balloon", "A chance", "A whistle", "A bubble"],
    answerIndex: 1,
    aha: "You blow a chance by missing it, an idiom unlike puffing up a balloon.",
  },
  {
    question: "What kind of seal can't swim or bark?",
    choices: ["A harbor seal", "A wax seal", "A fur seal", "An elephant seal"],
    answerIndex: 1,
    aha: "A wax seal closes a letter and has nothing to do with the animal.",
  },
  {
    question: "What has a palm and a heart but no pulse?",
    choices: ["A nurse", "A hand of cards", "A tree", "A clock"],
    answerIndex: 2,
    aha: "A palm tree shares its name with your palm, and a tree's core is its heart.",
  },
  {
    question: "What can you draw out for hours without lifting a pencil?",
    choices: ["A picture", "A meeting", "A line", "A map"],
    answerIndex: 1,
    aha: "A meeting that drags on is drawn out in time, not in ink.",
  },
  {
    question: "What kind of mole digs through no dirt at all?",
    choices: ["A garden mole", "A spy mole", "A star-nosed mole", "A mole on skin"],
    answerIndex: 1,
    aha: "A spy mole burrows inside an organization, not the ground.",
  },
  {
    question: "What is shaved every morning yet never grows a beard?",
    choices: ["A barber", "Ice for a snow cone", "A razor", "A chin"],
    answerIndex: 1,
    aha: "Ice is shaved to make a snow cone, a meaning of shave with no whiskers.",
  },
  {
    question: "What kind of crane lifts nothing off the ground?",
    choices: ["A tower crane", "A paper crane", "A mobile crane", "A construction crane"],
    answerIndex: 1,
    aha: "A folded paper crane is origami art, not a lifting machine.",
  },
  {
    question: "What can you spin without a wheel and weave without thread?",
    choices: ["Cloth", "A tale", "A web", "A coin"],
    answerIndex: 1,
    aha: "You spin a tale and weave a story, crafting it from words alone.",
  },
  {
    question: "What has a head of foam but never washes its hair?",
    choices: ["A wave", "A root beer", "A bath", "A cloud"],
    answerIndex: 1,
    aha: "A glass of root beer wears a frothy head of foam on top.",
  },
  {
    question: "What kind of trip never takes you anywhere?",
    choices: ["A road trip", "A trip over a rug", "A field trip", "A guilt trip"],
    answerIndex: 1,
    aha: "Tripping over a rug is a stumble, leaving you exactly where you fell.",
  },
  {
    question: "What can be square yet have no corners, and round yet not roll?",
    choices: ["A meal", "A wheel", "A box", "A ring"],
    answerIndex: 0,
    aha: "A square meal is a hearty one and a round of food is a serving, both figures of speech.",
  },
  {
    question: "What kind of note will never make a sound?",
    choices: ["A whole note", "A banknote", "A high note", "A grace note"],
    answerIndex: 1,
    aha: "A banknote is paper money, silent no matter how you handle it.",
  },
  {
    question: "What has a cap you cannot wear and a bottom you cannot sit on?",
    choices: ["A chair", "A bottle", "A mountain", "A jar"],
    answerIndex: 1,
    aha: "A bottle has a cap on top and a bottom at the base, neither for a person.",
  },
  {
    question: "What kind of bug lives in your ear without ever crawling there?",
    choices: ["A ladybug", "An earworm", "A bedbug", "A cricket"],
    answerIndex: 1,
    aha: "An earworm is a catchy tune stuck in your head, not a real insect.",
  },
  {
    question: "What can be picked but never with fingers, and broken but never with hands?",
    choices: ["A flower", "A lock", "A fruit", "A scab"],
    answerIndex: 1,
    aha: "A lock is picked with a tool and broken open, neither using bare fingers in the usual sense.",
  },
  {
    question: "What kind of beat leaves no bruise?",
    choices: ["A police beat", "A drumbeat", "A heartbeat", "A wing beat"],
    answerIndex: 1,
    aha: "A drumbeat is rhythm you hear, not a blow that injures.",
  },
  {
    question: "What stretches across the whole sky yet you can fold it in your pocket?",
    choices: ["A rainbow", "A sky map", "A cloud", "The horizon"],
    answerIndex: 1,
    aha: "A star chart maps the entire sky and folds neatly away.",
  },
  {
    question: "What kind of well never holds a drop of water?",
    choices: ["A wishing well", "A stairwell", "An oil well", "A deep well"],
    answerIndex: 1,
    aha: "A stairwell is the shaft a staircase climbs, dry from top to bottom.",
  },
  {
    question: "What can you catch off guard but never with a net?",
    choices: ["A fish", "Someone", "A ball", "A cold"],
    answerIndex: 1,
    aha: "You catch someone off guard by surprising them, no net needed.",
  },
  {
    question: "What kind of frog gives you a voice instead of warts?",
    choices: ["A tree frog", "A frog in your throat", "A bullfrog", "A poison frog"],
    answerIndex: 1,
    aha: "A frog in your throat is a hoarse, croaky voice, not an amphibian.",
  },
  {
    question: "What has rungs to climb but takes you nowhere new?",
    choices: ["A staircase", "A career ladder", "A rope bridge", "A fire escape"],
    answerIndex: 1,
    aha: "A career ladder is a figure of speech for advancement, with no physical steps.",
  },
  {
    question: "What kind of shower never gets you clean?",
    choices: ["A cold shower", "A meteor shower", "A baby shower's cake", "A rain shower"],
    answerIndex: 1,
    aha: "A meteor shower is streaks of light across the sky, no water involved.",
  },
  {
    question: "What can you draw a blank on but never on paper?",
    choices: ["A sketch", "A memory", "A map", "A portrait"],
    answerIndex: 1,
    aha: "To draw a blank is to fail to recall something, no pencil required.",
  },
  {
    question: "What kind of mint has nothing to do with your breath?",
    choices: ["A peppermint", "A coin mint", "A spearmint", "A breath mint"],
    answerIndex: 1,
    aha: "A mint is where coins are made, sharing only a name with the candy.",
  },
  {
    question: "What is taken from a mine, shut in a wooden case, yet used by almost everyone?",
    choices: ["A diamond", "Pencil lead", "Coal", "Gold"],
    answerIndex: 1,
    aha: "Graphite is mined, encased in a wooden pencil, and used the world over.",
  },
  {
    question: "What kind of letter can you not read?",
    choices: ["A love letter", "The letter B", "A chain letter", "A cover letter"],
    answerIndex: 1,
    aha: "A single letter of the alphabet, like B, is a symbol you sound out rather than read as a message.",
  },
  {
    question: "What has a ladder but you can never climb it?",
    choices: ["A fire truck", "A run in a stocking", "A treehouse", "A pool"],
    answerIndex: 1,
    aha: "A run in a stocking is called a ladder in some places, far too delicate to climb.",
  },
  {
    question: "What kind of train carries no passengers and burns no coal?",
    choices: ["A freight train", "A train of thought", "A steam train", "A subway train"],
    answerIndex: 1,
    aha: "A train of thought is a chain of ideas, carrying nothing physical.",
  },
  {
    question: "What can you hatch without an egg?",
    choices: ["A chick", "A plan", "A bird", "A dragon"],
    answerIndex: 1,
    aha: "You hatch a plan or a scheme, no shell required.",
  },
  {
    question: "What kind of stage holds no actors and never moves?",
    choices: ["A theater stage", "A stage of life", "A concert stage", "A rocket stage"],
    answerIndex: 1,
    aha: "A stage of life is a phase you pass through, not a platform.",
  },
  {
    question: "What can you keep your eye on without ever seeing it?",
    choices: ["A target", "The ball", "The prize", "A goal"],
    answerIndex: 2,
    aha: "Keeping your eye on the prize means staying focused on a goal you cannot literally watch.",
  },
  {
    question: "What kind of spring will never make you bounce?",
    choices: ["A bed spring", "The season of spring", "A coil spring", "A trampoline spring"],
    answerIndex: 1,
    aha: "Spring the season is a time of year, not a springy coil.",
  },
  {
    question: "What runs but has no legs, and bites but has no teeth?",
    choices: ["A snake", "Frost", "A river", "A clock"],
    answerIndex: 1,
    aha: "Frost runs across the ground overnight and bites your skin with cold.",
  },
  {
    question: "What kind of class will never grade your homework?",
    choices: ["A math class", "First class on a plane", "A science class", "An art class"],
    answerIndex: 1,
    aha: "First class is a level of comfort, not a teacher with a red pen.",
  },
  {
    question: "What can you turn over without lifting a thing?",
    choices: ["A pancake", "A new leaf", "A card", "A stone"],
    answerIndex: 1,
    aha: "To turn over a new leaf means to start fresh, nothing actually flipped.",
  },
  {
    question: "What kind of organ makes music but never beats?",
    choices: ["A heart", "A pipe organ", "A liver", "A lung"],
    answerIndex: 1,
    aha: "A pipe organ fills a hall with sound and has no pulse at all.",
  },
  {
    question: "What can be lent but never returned the same?",
    choices: ["A book", "An ear", "A pen", "A coin"],
    answerIndex: 1,
    aha: "You lend someone your ear by listening, and the moment never comes back unchanged.",
  },
  {
    question: "What kind of cell holds no prisoner and no battery?",
    choices: ["A jail cell", "A spreadsheet cell", "A solar cell", "A phone cell"],
    answerIndex: 1,
    aha: "A spreadsheet cell is a box for data, locking up nothing.",
  },
  {
    question: "What can you break in the morning before you eat anything?",
    choices: ["A plate", "Your fast", "An egg", "The silence"],
    answerIndex: 1,
    aha: "You break your fast with breakfast, which is exactly what the word means.",
  },
  {
    question: "What kind of bolt brings no lightning and locks no door?",
    choices: ["A deadbolt", "A bolt of fabric", "A thunderbolt", "A door bolt"],
    answerIndex: 1,
    aha: "A bolt of fabric is a rolled length of cloth, quiet and unlocking nothing.",
  },
  {
    question: "What gets driven home but never parks in a garage?",
    choices: ["A car", "A point", "A nail", "A truck"],
    answerIndex: 1,
    aha: "You drive a point home by making it clearly understood.",
  },
  {
    question: "What kind of root grows in your mouth, not the soil?",
    choices: ["A tree root", "A tooth root", "A carrot root", "A square root"],
    answerIndex: 1,
    aha: "A tooth's root anchors it in your gum, no garden required.",
  },
  {
    question: "What can you raise without lifting and lower without dropping?",
    choices: ["A flag", "Your voice", "A bucket", "A sail"],
    answerIndex: 1,
    aha: "You raise and lower your voice by changing its volume, not its height.",
  },
  {
    question: "What kind of chip has nothing to do with a computer or a snack?",
    choices: ["A potato chip", "A chip on your shoulder", "A microchip", "A poker chip"],
    answerIndex: 1,
    aha: "A chip on your shoulder is a grudge, purely a state of mind.",
  },
  {
    question: "What can you hold a grudge with but never your hands?",
    choices: ["A fist", "A heart", "A grip", "An arm"],
    answerIndex: 1,
    aha: "You hold a grudge in your heart, an emotion no hand can grasp.",
  },
  {
    question: "What kind of fork will never touch your food?",
    choices: ["A salad fork", "A fork in the road", "A dinner fork", "A serving fork"],
    answerIndex: 1,
    aha: "A fork in the road is a place where it splits, not a utensil.",
  },
  {
    question: "What can you lose your way in without ever stepping inside?",
    choices: ["A forest", "A thought", "A maze", "A city"],
    answerIndex: 1,
    aha: "You can lose your way in a thought or a daydream while sitting perfectly still.",
  },
  {
    question: "What kind of cabinet has no shelves and no drawers?",
    choices: ["A kitchen cabinet", "A government cabinet", "A filing cabinet", "A medicine cabinet"],
    answerIndex: 1,
    aha: "A government cabinet is a group of advisors, holding no dishes or files.",
  },
  {
    question: "What can you blow off but never blow out?",
    choices: ["A candle", "An appointment", "A match", "A flame"],
    answerIndex: 1,
    aha: "You blow off an appointment by skipping it, an idiom with no breath involved.",
  },
  {
    question: "What kind of pipe carries a tune instead of water?",
    choices: ["A drainpipe", "A set of bagpipes", "A water pipe", "An exhaust pipe"],
    answerIndex: 1,
    aha: "Bagpipes carry a melody through their pipes, never a drop of water.",
  },
  {
    question: "What can you make up without inventing a thing?",
    choices: ["A story", "A bed", "An excuse", "A rule"],
    answerIndex: 1,
    aha: "You make up a bed by tidying it, a meaning that invents nothing.",
  },
  {
    question: "What kind of bow makes no sound and shoots no arrow?",
    choices: ["A violin bow", "A bow of respect", "A hunting bow", "A crossbow"],
    answerIndex: 1,
    aha: "A bow of respect is a polite bend at the waist, silent and unarmed.",
  },
  {
    question: "What can you catch a glimpse of but never hold?",
    choices: ["A fish", "A glance", "A ball", "A coin"],
    answerIndex: 1,
    aha: "A glimpse is a brief look that vanishes the instant it happens.",
  },
  {
    question: "What kind of plant will never need watering?",
    choices: ["A house plant", "A power plant", "A garden plant", "A potted plant"],
    answerIndex: 1,
    aha: "A power plant generates electricity, sharing only its name with greenery.",
  },
  {
    question: "What can you take a rain check on without any rain?",
    choices: ["An umbrella", "An invitation", "A weather report", "A picnic"],
    answerIndex: 1,
    aha: "To take a rain check on an invitation is to postpone it, no weather needed.",
  },
  {
    question: "What kind of board meets but never gets nailed down?",
    choices: ["A diving board", "A board of directors", "A floorboard", "A skateboard"],
    answerIndex: 1,
    aha: "A board of directors is a group of people who meet, not a plank.",
  },
  {
    question: "What can you pull off without using any hands?",
    choices: ["A sticker", "A victory", "A glove", "A bandage"],
    answerIndex: 1,
    aha: "You pull off a victory by succeeding, an achievement requiring no grip.",
  },
  {
    question: "What kind of arm has no hand and bends no elbow?",
    choices: ["A right arm", "An arm of the law", "A strong arm", "A broken arm"],
    answerIndex: 1,
    aha: "The arm of the law is the reach of authority, not a limb.",
  },
  {
    question: "What can you run up without taking a single step?",
    choices: ["A hill", "A bill", "A staircase", "A ladder"],
    answerIndex: 1,
    aha: "You run up a bill by spending, climbing nothing at all.",
  },
  {
    question: "What kind of belt holds up no trousers and spins no machine?",
    choices: ["A leather belt", "An asteroid belt", "A seat belt", "A fan belt"],
    answerIndex: 1,
    aha: "An asteroid belt is a ring of space rocks, holding nothing up.",
  },
  {
    question: "What can you break the ice with but never with a pick?",
    choices: ["A glacier", "A stranger", "A frozen lake", "A hammer"],
    answerIndex: 1,
    aha: "You break the ice with a stranger by starting a friendly chat.",
  },
  {
    question: "What kind of patch will never mend a hole?",
    choices: ["A fabric patch", "A patch of fog", "A bike patch", "An eye patch"],
    answerIndex: 1,
    aha: "A patch of fog is a stretch of mist, repairing nothing.",
  },
  {
    question: "What can you save without a bank and spend without a coin?",
    choices: ["Money", "Energy", "Gold", "Notes"],
    answerIndex: 1,
    aha: "You save and spend energy through your effort, with no money changing hands.",
  },
  {
    question: "What kind of horse will never gallop?",
    choices: ["A racehorse", "A clothes horse", "A workhorse", "A wild horse"],
    answerIndex: 1,
    aha: "A clothes horse is a rack for drying laundry, going nowhere.",
  },
  {
    question: "What can you hold your tongue with but never your fingers?",
    choices: ["A clamp", "Self-control", "A clip", "A glove"],
    answerIndex: 1,
    aha: "To hold your tongue is to stay quiet through self-control, no touching needed.",
  },
  {
    question: "What kind of court is shaped by a king but plays no sport?",
    choices: ["A tennis court", "A royal court", "A basketball court", "A squash court"],
    answerIndex: 1,
    aha: "A royal court is the people surrounding a monarch, not a playing surface.",
  },
  {
    question: "What can you bury without a shovel and dig up without dirt?",
    choices: ["A bone", "The past", "Treasure", "A seed"],
    answerIndex: 1,
    aha: "You bury the past by forgetting it and dig it up by recalling it.",
  },
  {
    question: "What kind of drop will never splash?",
    choices: ["A raindrop", "A price drop", "A dewdrop", "A teardrop"],
    answerIndex: 1,
    aha: "A price drop is a fall in cost, splashing no one.",
  },
  {
    question: "What can you lend a hand with but never your actual hand?",
    choices: ["A handshake", "A favor", "A high five", "A glove"],
    answerIndex: 1,
    aha: "Lending a hand means doing someone a favor, no limb detached.",
  },
  {
    question: "What kind of wing can fly no plane and grow no feathers?",
    choices: ["A bird's wing", "A wing of a building", "A bat's wing", "A plane's wing"],
    answerIndex: 1,
    aha: "A wing of a building is a section of it, motionless and bare.",
  },
  {
    question: "What can you call off without making a phone call?",
    choices: ["A dog", "An event", "A name", "A taxi"],
    answerIndex: 1,
    aha: "To call off an event is to cancel it, no telephone involved.",
  },
];
