import type { ThemeEntry } from "./engine";

/**
 * The Mind Strands theme bank. Each entry is a category with a spangram (which
 * spans the grid) and a generous pool of on-theme words. The generator selects
 * a subset of the pool whose lengths plus the spangram total exactly 48 letters
 * (the 6×8 grid), then packs them. Pools are deliberately oversized with varied
 * lengths so a 48-letter subset (4–8 words) always exists for the packer.
 *
 * Words are uppercase A–Z only. Every entry is validated in engine.test.ts.
 */
export const BANK: ThemeEntry[] = [
  {
    name: "BRAIN ANATOMY",
    spangram: "CEREBRUM",
    words: ["CORTEX", "NEURON", "SYNAPSE", "AXON", "MEMORY", "DENDRITE", "LOBE", "STEM", "THALAMUS", "PONS", "GLIA", "NERVE"],
    insight: "The cerebrum is the brain's largest region — its folded cortex handles thought, language and voluntary action across two mirror-image hemispheres.",
  },
  {
    name: "MEMORY TRICKS",
    spangram: "MNEMONICS",
    words: ["RECALL", "CHUNK", "REPEAT", "SPACING", "ANCHOR", "REVIEW", "CUE", "PEG", "STORY", "IMAGE", "LINK", "RHYME"],
    insight: "Spacing your study sessions and chunking information into meaningful groups dramatically strengthen long-term memory storage.",
  },
  {
    name: "HOW WE LEARN",
    spangram: "PLASTICITY",
    words: ["PRACTICE", "REPEAT", "RECALL", "FOCUS", "ERROR", "HABIT", "SKILL", "DRILL", "STUDY", "EFFORT", "RETRY", "GROW"],
    insight: "Your brain physically rewires itself as you learn — new neural pathways form with practice, even well into adulthood.",
  },
  {
    name: "STAYING FOCUSED",
    spangram: "ATTENTION",
    words: ["FOCUS", "ALERT", "FILTER", "IGNORE", "TARGET", "SCAN", "TRACK", "NOTICE", "AWARE", "ZONE", "GAZE", "WATCH"],
    insight: "Attention works like a spotlight: focusing on one thing dims everything else, which is why multitasking quietly drains accuracy.",
  },
  {
    name: "FEELING IT",
    spangram: "AMYGDALA",
    words: ["FEAR", "JOY", "ANGER", "TRUST", "MOOD", "STRESS", "CALM", "PANIC", "RELIEF", "DREAD", "WORRY", "PRIDE"],
    insight: "Your amygdala can flag a threat in milliseconds, often firing before your conscious mind has even registered what happened.",
  },
  {
    name: "SLEEP CYCLE",
    spangram: "CIRCADIAN",
    words: ["DREAM", "REST", "NAP", "WAKE", "NIGHT", "MELATONIN", "DEEP", "SNORE", "DROWSY", "YAWN", "DOZE", "PILLOW"],
    insight: "Deep sleep clears metabolic waste from the brain and consolidates the day's memories into durable long-term storage.",
  },
  {
    name: "THE SENSES",
    spangram: "PERCEPTION",
    words: ["SIGHT", "SOUND", "TASTE", "SMELL", "TOUCH", "SENSE", "HEAR", "FEEL", "ODOR", "VISION", "FLAVOR", "NOISE"],
    insight: "Perception is your brain's best guess — it constantly predicts the world and corrects itself against incoming sensory data.",
  },
  {
    name: "BIG IDEAS",
    spangram: "CREATIVITY",
    words: ["IDEA", "MUSE", "SPARK", "DREAM", "DESIGN", "INVENT", "VISION", "CRAFT", "NOVEL", "FLAIR", "ORIGINAL", "IMAGINE"],
    insight: "Creative insight often arrives during mind-wandering, when the brain's default-mode network links distant ideas in fresh ways.",
  },
  {
    name: "SOLAR SYSTEM",
    spangram: "PLANETARY",
    words: ["MARS", "VENUS", "EARTH", "SATURN", "COMET", "MOON", "ORBIT", "PLUTO", "SUN", "URANUS", "NEPTUNE", "METEOR"],
    insight: "The brain builds spatial maps using grid cells — the same machinery that helps you imagine the layout of the solar system.",
  },
  {
    name: "WEATHER WATCH",
    spangram: "ATMOSPHERE",
    words: ["RAIN", "STORM", "CLOUD", "WIND", "SNOW", "FROST", "THUNDER", "MIST", "HAIL", "SLEET", "BREEZE", "GALE"],
    insight: "Predicting weather, like predicting anything, taps the brain's prefrontal cortex, which models likely futures from past patterns.",
  },
  {
    name: "OCEAN LIFE",
    spangram: "UNDERWATER",
    words: ["CORAL", "SHARK", "WHALE", "SQUID", "REEF", "TIDE", "WAVE", "EEL", "CRAB", "OCTOPUS", "SEAL", "RAY"],
    insight: "Octopuses have neurons distributed through their arms, a strikingly different design from the centralized vertebrate brain.",
  },
  {
    name: "IN THE GARDEN",
    spangram: "BOTANICAL",
    words: ["ROSE", "TULIP", "SEED", "LEAF", "PETAL", "STEM", "ROOT", "BLOOM", "SOIL", "SPROUT", "VINE", "BUD"],
    insight: "Spending time around greenery measurably lowers stress hormones and restores depleted attention in the prefrontal cortex.",
  },
  {
    name: "KITCHEN SPICES",
    spangram: "SEASONING",
    words: ["CUMIN", "BASIL", "THYME", "CLOVE", "GINGER", "MINT", "SAGE", "CHILI", "PEPPER", "NUTMEG", "DILL", "ANISE"],
    insight: "Smell links directly to memory: aromas route through the olfactory bulb straight to the hippocampus, evoking vivid recall.",
  },
  {
    name: "FRESH FRUIT",
    spangram: "ORCHARDS",
    words: ["APPLE", "MANGO", "GRAPE", "PEACH", "LEMON", "PLUM", "PEAR", "BERRY", "CHERRY", "MELON", "KIWI", "FIG"],
    insight: "Antioxidant-rich berries support memory; flavonoids appear to improve blood flow to memory-critical brain regions.",
  },
  {
    name: "MUSIC THEORY",
    spangram: "HARMONIES",
    words: ["TEMPO", "CHORD", "SCALE", "NOTE", "BEAT", "PITCH", "TUNE", "REST", "MELODY", "RHYTHM", "KEY", "OCTAVE"],
    insight: "Learning music engages motor, auditory and emotional circuits at once, building unusually dense cross-brain connections.",
  },
  {
    name: "ART STUDIO",
    spangram: "PALETTES",
    words: ["BRUSH", "CANVAS", "PAINT", "EASEL", "SHADE", "TONE", "INK", "FRAME", "SKETCH", "COLOR", "PASTEL", "CHALK"],
    insight: "Viewing art activates the brain's reward system, releasing dopamine much as food or social connection does.",
  },
  {
    name: "WORLD CITIES",
    spangram: "METROPOLIS",
    words: ["PARIS", "TOKYO", "CAIRO", "LIMA", "ROME", "OSLO", "DELHI", "SEOUL", "MADRID", "BERLIN", "DUBAI", "MILAN"],
    insight: "London taxi drivers grow a larger hippocampus from memorizing the city — a vivid example of adult neuroplasticity.",
  },
  {
    name: "MOUNTAIN RANGE",
    spangram: "ALTITUDES",
    words: ["PEAK", "RIDGE", "CLIFF", "SLOPE", "SUMMIT", "TRAIL", "ROCK", "VALLEY", "CRAG", "GORGE", "FACE", "SCREE"],
    insight: "At high altitude the brain adapts to thinner air by boosting blood flow and red-cell production over several days.",
  },
  {
    name: "RIVER JOURNEY",
    spangram: "TRIBUTARY",
    words: ["DELTA", "BANK", "FLOW", "RAPID", "BEND", "MOUTH", "SOURCE", "STREAM", "CURRENT", "EDDY", "FORD", "POOL"],
    insight: "The brain prefers to conserve energy, often choosing the cognitive path of least resistance — much like water finding its course.",
  },
  {
    name: "DESERT LANDS",
    spangram: "ARIDITY",
    words: ["DUNE", "OASIS", "CACTUS", "SAND", "CAMEL", "MIRAGE", "HEAT", "DRY", "DUST", "SCRUB", "BARREN", "WADI"],
    insight: "A mirage is your visual system misreading bent light — proof that perception is interpretation, not raw recording.",
  },
  {
    name: "BIRD WATCHING",
    spangram: "PLUMAGE",
    words: ["ROBIN", "FINCH", "HAWK", "WREN", "CROW", "DOVE", "OWL", "HERON", "EAGLE", "SPARROW", "STORK", "JAY"],
    insight: "Some birds shrink and regrow brain regions seasonally to learn new songs — a dramatic form of neural plasticity.",
  },
  {
    name: "JUNGLE CREATURES",
    spangram: "PRIMATES",
    words: ["TIGER", "SLOTH", "GECKO", "TAPIR", "MACAW", "FROG", "ANT", "JAGUAR", "MONKEY", "PARROT", "SNAKE", "LEMUR"],
    insight: "Primate brains devote enormous resources to vision and social tracking, which helped our own intelligence evolve.",
  },
  {
    name: "WINTER SPORTS",
    spangram: "TOBOGGAN",
    words: ["SKI", "SKATE", "SLED", "CURL", "LUGE", "JUMP", "GLIDE", "CARVE", "HOCKEY", "SLALOM", "BOARD", "RINK"],
    insight: "Balancing on skis trains the cerebellum, the brain's coordination center that smooths and fine-tunes every movement.",
  },
  {
    name: "BALL GAMES",
    spangram: "ATHLETICS",
    words: ["GOAL", "SERVE", "PITCH", "DRIBBLE", "PASS", "KICK", "SHOOT", "DUNK", "SCORE", "VOLLEY", "TACKLE", "SPIKE"],
    insight: "Expert athletes show faster neural processing in motion-prediction areas, reacting before slower conscious thought kicks in.",
  },
  {
    name: "BOARD GAMES",
    spangram: "STRATEGY",
    words: ["CHESS", "DICE", "PAWN", "MOVE", "ROOK", "TILE", "TURN", "PIECE", "BOARD", "TOKEN", "KNIGHT", "BISHOP"],
    insight: "Strategic games strengthen working memory and planning by forcing the prefrontal cortex to simulate moves ahead.",
  },
  {
    name: "CARD PLAY",
    spangram: "SHUFFLES",
    words: ["ACE", "KING", "QUEEN", "JACK", "DEAL", "BLUFF", "HAND", "SUIT", "TRUMP", "SPADE", "HEART", "CLUB"],
    insight: "Bluffing recruits theory-of-mind circuits as you model what your opponent believes you believe.",
  },
  {
    name: "TASTY BREAKFAST",
    spangram: "PANCAKES",
    words: ["TOAST", "EGGS", "BACON", "JAM", "OATS", "JUICE", "WAFFLE", "CEREAL", "BAGEL", "MUFFIN", "HONEY", "BUTTER"],
    insight: "Glucose from breakfast fuels neurons directly; the brain burns about a fifth of your daily energy despite its small size.",
  },
  {
    name: "BAKING DAY",
    spangram: "KNEADING",
    words: ["FLOUR", "DOUGH", "YEAST", "SUGAR", "OVEN", "LOAF", "CRUST", "WHISK", "BATTER", "ROLL", "PROOF", "GLAZE"],
    insight: "Repetitive, hands-on tasks like kneading can induce a calming flow state that quiets the brain's worry network.",
  },
  {
    name: "COFFEE BREAK",
    spangram: "CAFFEINE",
    words: ["BEAN", "BREW", "MUG", "FOAM", "ROAST", "DRIP", "LATTE", "MOCHA", "CREAM", "GRIND", "CUP", "STEAM"],
    insight: "Caffeine blocks adenosine, the molecule that builds up sleep pressure, temporarily masking the brain's sense of fatigue.",
  },
  {
    name: "TOOLBOX",
    spangram: "HARDWARE",
    words: ["DRILL", "SAW", "NAIL", "BOLT", "WRENCH", "HAMMER", "VISE", "FILE", "PLIERS", "SCREW", "CHISEL", "CLAMP"],
    insight: "Tool use lit up planning and motor circuits in early humans, a feedback loop that helped push brain size upward.",
  },
  {
    name: "CLOTHING",
    spangram: "WARDROBE",
    words: ["SHIRT", "JEANS", "SCARF", "GLOVE", "BOOT", "COAT", "SOCK", "HAT", "DRESS", "JACKET", "BELT", "SWEATER"],
    insight: "Recognizing a familiar outfit relies on the fusiform area, the same region that specializes in spotting faces.",
  },
  {
    name: "ON THE FARM",
    spangram: "LIVESTOCK",
    words: ["COW", "PIG", "HEN", "GOAT", "SHEEP", "BARN", "PLOW", "FIELD", "TRACTOR", "HORSE", "FENCE", "SILO"],
    insight: "Animals navigating familiar pastures use the same hippocampal place cells that build your own mental maps.",
  },
  {
    name: "DINOSAUR ERA",
    spangram: "FOSSILIZED",
    words: ["TREX", "RAPTOR", "BONE", "SCALE", "CLAW", "EGG", "HORN", "TAIL", "SPIKE", "JAW", "STEGO", "REPTILE"],
    insight: "Endocasts of dinosaur skulls let scientists reconstruct ancient brains and infer surprising senses and behaviors.",
  },
  {
    name: "ROCK TYPES",
    spangram: "MINERALS",
    words: ["GRANITE", "SLATE", "QUARTZ", "CHALK", "BASALT", "GEM", "ORE", "FLINT", "SHALE", "MARBLE", "CLAY", "PUMICE"],
    insight: "Categorizing objects like rocks engages the brain's semantic networks, which file knowledge by shared features.",
  },
  {
    name: "CHEMISTRY LAB",
    spangram: "MOLECULES",
    words: ["ATOM", "ACID", "BASE", "IONS", "BOND", "GAS", "SALT", "MIX", "FLASK", "BEAKER", "VAPOR", "SOLVENT"],
    insight: "Neurotransmitters are simple molecules, yet tiny shifts in their balance dramatically alter mood and cognition.",
  },
  {
    name: "MATH WORLD",
    spangram: "EQUATIONS",
    words: ["SUM", "PRIME", "ANGLE", "GRAPH", "RATIO", "PROOF", "LOGIC", "DIGIT", "FACTOR", "VECTOR", "SET", "POWER"],
    insight: "Doing math activates the intraparietal sulcus, a region that represents quantity even in pre-verbal infants.",
  },
  {
    name: "COMPUTER PARTS",
    spangram: "PROCESSOR",
    words: ["CHIP", "RAM", "DISK", "CABLE", "MOUSE", "SCREEN", "PORT", "DRIVE", "BOARD", "FAN", "MEMORY", "CACHE"],
    insight: "The brain is wildly more energy-efficient than any computer, running on roughly the wattage of a dim light bulb.",
  },
  {
    name: "SPACE TRAVEL",
    spangram: "ASTRONAUT",
    words: ["ROCKET", "LAUNCH", "ORBIT", "CREW", "SUIT", "MOON", "STAR", "PROBE", "SHUTTLE", "BOOSTER", "PAD", "HATCH"],
    insight: "In weightlessness the brain quickly recalibrates balance, remapping which signals to trust from the inner ear and eyes.",
  },
  {
    name: "ANCIENT EGYPT",
    spangram: "PYRAMIDS",
    words: ["PHARAOH", "SPHINX", "NILE", "TOMB", "SCROLL", "MUMMY", "GOLD", "SAND", "TEMPLE", "OBELISK", "REED", "GLYPH"],
    insight: "Reading hieroglyphs, like any script, recruits a brain region that learning literally repurposes from object recognition.",
  },
  {
    name: "MYTHOLOGY",
    spangram: "LEGENDARY",
    words: ["TITAN", "HYDRA", "OMEN", "ORACLE", "QUEST", "HERO", "MUSE", "FATE", "NYMPH", "PHOENIX", "GOD", "BEAST"],
    insight: "Stories stick because the brain encodes narrative far more readily than disconnected facts, linking cause to consequence.",
  },
  {
    name: "CASTLE LIFE",
    spangram: "MEDIEVAL",
    words: ["KNIGHT", "MOAT", "TOWER", "SWORD", "CROWN", "GATE", "ARMOR", "KING", "QUEEN", "SHIELD", "KEEP", "LANCE"],
    insight: "Vivid imagery, like a fortress, makes information memorable — the basis of the ancient memory-palace technique.",
  },
  {
    name: "DETECTIVE WORK",
    spangram: "MYSTERIES",
    words: ["CLUE", "ALIBI", "MOTIVE", "SUSPECT", "PROOF", "CASE", "TRACE", "SOLVE", "WITNESS", "HUNCH", "LEAD", "CRIME"],
    insight: "Solving puzzles rewards the brain with a dopamine 'aha' hit, reinforcing the persistence that cracked the problem.",
  },
  {
    name: "EMOTIONS",
    spangram: "FEELINGS",
    words: ["HAPPY", "SAD", "ANGRY", "PROUD", "SHY", "BORED", "GLAD", "TENSE", "CALM", "EAGER", "JOY", "GRIEF"],
    insight: "Naming an emotion calms the amygdala — putting feelings into words measurably reduces their intensity.",
  },
  {
    name: "BODY SYSTEMS",
    spangram: "CIRCULATION",
    words: ["HEART", "LUNG", "VEIN", "NERVE", "BONE", "MUSCLE", "SKIN", "GLAND", "ARTERY", "KIDNEY", "LIVER", "SPINE"],
    insight: "Your brain claims about 20 percent of your blood flow and oxygen, far out of proportion to its modest weight.",
  },
  {
    name: "FIVE TASTES",
    spangram: "FLAVORFUL",
    words: ["SWEET", "SOUR", "SALTY", "BITTER", "SPICY", "TANGY", "RICH", "MILD", "UMAMI", "ZESTY", "SHARP", "SMOKY"],
    insight: "Flavor is multisensory — most of what you 'taste' is actually smell, which is why food seems flat with a head cold.",
  },
  {
    name: "WEATHER MOODS",
    spangram: "SUNSHINE",
    words: ["BREEZE", "DRIZZLE", "GUST", "HAZE", "CHILL", "WARM", "DAMP", "CLEAR", "MUGGY", "CRISP", "BALMY", "FOGGY"],
    insight: "Bright light boosts serotonin, which is partly why sunny days tend to lift mood and sharpen alertness.",
  },
  {
    name: "TIME WORDS",
    spangram: "CALENDAR",
    words: ["HOUR", "WEEK", "MONTH", "YEAR", "DAWN", "DUSK", "NOON", "ERA", "MINUTE", "SECOND", "DECADE", "EPOCH"],
    insight: "The brain has no single clock; it stitches together overlapping rhythms to build your fluid sense of passing time.",
  },
  {
    name: "COLORS",
    spangram: "SPECTRUM",
    words: ["RED", "BLUE", "GREEN", "AMBER", "TEAL", "PINK", "GOLD", "GRAY", "VIOLET", "INDIGO", "OLIVE", "CORAL"],
    insight: "Color isn't in the world but in the head: your brain constructs hue from how cone cells compare wavelengths of light.",
  },
  {
    name: "SHAPES",
    spangram: "GEOMETRY",
    words: ["CIRCLE", "SQUARE", "OVAL", "CUBE", "CONE", "STAR", "ARC", "PRISM", "SPHERE", "PYRAMID", "RHOMBUS", "DISK"],
    insight: "The brain spots shapes by detecting edges and angles in the visual cortex before assembling them into whole objects.",
  },
  {
    name: "READING TIME",
    spangram: "LIBRARY",
    words: ["NOVEL", "PAGE", "CHAPTER", "PLOT", "PROSE", "INDEX", "STORY", "VERSE", "AUTHOR", "SPINE", "TITLE", "GENRE"],
    insight: "Deep reading builds dense connections between language and imagination centers, strengthening focus over time.",
  },
  {
    name: "WRITING TOOLS",
    spangram: "PENMANSHIP",
    words: ["PEN", "INK", "QUILL", "PAPER", "DRAFT", "EDIT", "WORD", "NOTE", "PENCIL", "ERASER", "MARGIN", "TYPE"],
    insight: "Writing by hand activates motor and memory circuits more richly than typing, which can deepen learning.",
  },
  {
    name: "TRANSPORT",
    spangram: "VEHICLES",
    words: ["TRAIN", "BUS", "TRAM", "FERRY", "BIKE", "CAR", "TAXI", "VAN", "TRUCK", "SCOOTER", "WAGON", "BOAT"],
    insight: "Navigating routes exercises the hippocampus; over-relying on GPS may quietly weaken this natural mapping ability.",
  },
  {
    name: "AIR TRAVEL",
    spangram: "AIRCRAFT",
    words: ["JET", "WING", "PILOT", "RUNWAY", "CABIN", "GATE", "FLIGHT", "TAIL", "ENGINE", "TICKET", "RADAR", "AISLE"],
    insight: "Jet lag is your circadian clock lagging behind the new time zone, slowly resyncing to the local light schedule.",
  },
  {
    name: "INSECT WORLD",
    spangram: "ANTENNAE",
    words: ["BEE", "ANT", "MOTH", "WASP", "BEETLE", "FLY", "APHID", "GNAT", "CRICKET", "LOCUST", "MANTIS", "WEEVIL"],
    insight: "Honeybee brains, smaller than a grass seed, still master counting, navigation and symbolic learning.",
  },
  {
    name: "PET ANIMALS",
    spangram: "COMPANION",
    words: ["DOG", "CAT", "FISH", "BIRD", "RABBIT", "MOUSE", "FERRET", "GECKO", "HAMSTER", "PARROT", "PUPPY", "KITTEN"],
    insight: "Petting an animal lowers cortisol and raises oxytocin, easing the brain's stress response within minutes.",
  },
  {
    name: "TREE SPECIES",
    spangram: "FORESTRY",
    words: ["OAK", "PINE", "MAPLE", "BIRCH", "CEDAR", "ELM", "ASH", "WILLOW", "SPRUCE", "POPLAR", "BEECH", "ASPEN"],
    insight: "Forest walks reduce mental fatigue, restoring the directed attention that city environments steadily drain.",
  },
  {
    name: "GEMSTONES",
    spangram: "JEWELRY",
    words: ["RUBY", "OPAL", "PEARL", "JADE", "TOPAZ", "AMBER", "ONYX", "GARNET", "EMERALD", "AGATE", "BERYL", "ZIRCON"],
    insight: "Spotting a sparkle grabs attention automatically — the brain is wired to notice shine, an ancient cue for water.",
  },
  {
    name: "WATER FORMS",
    spangram: "HYDRATION",
    words: ["LAKE", "POND", "RIVER", "WAVE", "ICE", "STEAM", "MIST", "RAIN", "BROOK", "OCEAN", "PUDDLE", "DROP"],
    insight: "Even mild dehydration impairs concentration and short-term memory, since neurons depend on steady fluid balance.",
  },
  {
    name: "VOLCANO",
    spangram: "ERUPTION",
    words: ["LAVA", "ASH", "MAGMA", "CRATER", "VENT", "ROCK", "PLUME", "DOME", "CALDERA", "FLOW", "STEAM", "EMBER"],
    insight: "A sudden eruption triggers the brain's fast threat pathway, flooding the body with adrenaline before you can think.",
  },
  {
    name: "PUZZLE TYPES",
    spangram: "CROSSWORD",
    words: ["MAZE", "SUDOKU", "RIDDLE", "CIPHER", "LOGIC", "JIGSAW", "CODE", "CLUE", "ANAGRAM", "REBUS", "GRID", "QUIZ"],
    insight: "Varied puzzling keeps multiple cognitive domains active, which research links to sharper aging minds.",
  },
  {
    name: "DANCE STYLES",
    spangram: "BALLROOM",
    words: ["WALTZ", "TANGO", "SALSA", "SWING", "STEP", "SPIN", "LEAP", "TWIRL", "RUMBA", "FOXTROT", "JIVE", "SWAY"],
    insight: "Learning dance routines challenges memory and coordination together, a combo linked to better brain health with age.",
  },
  {
    name: "WEATHER SKY",
    spangram: "RAINBOWS",
    words: ["CLOUD", "SUN", "STORM", "BOLT", "HALO", "SLEET", "GUST", "DEW", "AURORA", "COMET", "MOON", "STAR"],
    insight: "A rainbow exists only from your vantage point — your brain assembles it from light bending through countless droplets.",
  },
  {
    name: "FAIRY TALE",
    spangram: "ENCHANTED",
    words: ["WITCH", "SPELL", "CROWN", "DRAGON", "WAND", "OGRE", "GOLD", "CURSE", "POTION", "GIANT", "TROLL", "FAIRY"],
    insight: "Imagining magical scenes lights up the same visual regions as actually seeing, blurring the line between sight and thought.",
  },
  {
    name: "VEGETABLE PATCH",
    spangram: "HARVESTED",
    words: ["CARROT", "ONION", "PEAS", "BEAN", "KALE", "BEET", "LEEK", "TURNIP", "CELERY", "RADISH", "SQUASH", "POTATO", "CHARD"],
    insight: "Leafy greens deliver folate and vitamin K that support healthy blood flow to the brain and may slow age-related decline.",
  },
  {
    name: "DAIRY GOODS",
    spangram: "CREAMERY",
    words: ["MILK", "CHEESE", "BUTTER", "YOGURT", "CURD", "WHEY", "CREAM", "GHEE", "KEFIR", "CUSTARD", "GELATO", "PANEER"],
    insight: "Fermented dairy like yogurt feeds gut microbes that communicate with the brain along the vagus nerve, influencing mood.",
  },
  {
    name: "PRECIOUS METALS",
    spangram: "ELEMENTAL",
    words: ["GOLD", "SILVER", "COPPER", "IRON", "ZINC", "LEAD", "NICKEL", "COBALT", "PLATINUM", "BRONZE", "BRASS", "STEEL", "PEWTER"],
    insight: "Trace metals like iron and zinc are essential cofactors for neurotransmitter production, so even mild deficits dull thinking.",
  },
  {
    name: "CITRUS GROVE",
    spangram: "TANGERINE",
    words: ["LEMON", "LIME", "ORANGE", "ZEST", "PULP", "RIND", "PITH", "CITRON", "POMELO", "KUMQUAT", "JUICE", "PEEL"],
    insight: "The sharp scent of citrus can boost alertness, as bright aromas nudge the brain toward a more wakeful, attentive state.",
  },
  {
    name: "STORMY SEAS",
    spangram: "MARITIME",
    words: ["WAVE", "SWELL", "FOAM", "GALE", "SQUALL", "SPRAY", "SURGE", "TIDE", "BRINE", "CURRENT", "CREST", "TROUGH"],
    insight: "The rhythmic motion of waves can lull the brain into relaxed alpha rhythms, which is why coastlines feel so calming.",
  },
  {
    name: "CAMPING TRIP",
    spangram: "WILDERNESS",
    words: ["TENT", "FIRE", "TRAIL", "ROPE", "STAKE", "LANTERN", "COMPASS", "CANTEEN", "STOVE", "PACK", "BOOTS", "EMBER"],
    insight: "Nights away from artificial light reset the body clock fast, shifting melatonin earlier and deepening restorative sleep.",
  },
  {
    name: "HONEY BEES",
    spangram: "POLLINATE",
    words: ["HIVE", "COMB", "DRONE", "QUEEN", "NECTAR", "SWARM", "STING", "LARVA", "FORAGE", "POLLEN", "CELL", "WINGS"],
    insight: "A foraging bee performs a waggle dance encoding direction and distance, a symbolic language driven by a tiny brain.",
  },
  {
    name: "VOLCANIC ROCK",
    spangram: "OBSIDIAN",
    words: ["BASALT", "PUMICE", "TUFF", "LAVA", "GLASS", "SCORIA", "MAGMA", "CINDER", "CRUST", "FLOW", "VENT", "DACITE"],
    insight: "Sorting rocks by texture trains the visual cortex to extract fine-grained features, sharpening pattern discrimination.",
  },
  {
    name: "AUTUMN SEASON",
    spangram: "HARVESTING",
    words: ["LEAF", "CRISP", "AMBER", "RAKE", "ACORN", "GOURD", "MAPLE", "FROST", "CHILL", "HAYRIDE", "CIDER", "CORN"],
    insight: "Falling daylight in autumn lowers serotonin for some people, a seasonal mood shift the brain tracks through the eyes.",
  },
  {
    name: "KNITTING CRAFT",
    spangram: "STITCHERY",
    words: ["YARN", "WOOL", "PURL", "CAST", "LOOP", "SKEIN", "NEEDLE", "PATTERN", "WEAVE", "FIBER", "SPOOL", "GAUGE"],
    insight: "Repetitive handwork like knitting can induce a meditative flow that quiets the brain's stress and rumination circuits.",
  },
  {
    name: "OPERA HOUSE",
    spangram: "SOPRANOS",
    words: ["ARIA", "TENOR", "DUET", "STAGE", "SCORE", "BARITONE", "ENCORE", "CHORUS", "LIBRETTO", "CURTAIN", "SOLO", "BASS"],
    insight: "Singing synchronizes breath, pitch and emotion, engaging motor and auditory networks that release mood-lifting endorphins.",
  },
  {
    name: "GLACIER ICE",
    spangram: "CREVASSE",
    words: ["BERG", "FROST", "SNOW", "FLOE", "SHEET", "MORAINE", "SERAC", "CALVE", "FREEZE", "POLAR", "DRIFT", "SLEET"],
    insight: "Cold exposure briefly heightens alertness as the brain ramps up noradrenaline to keep the body and mind sharp.",
  },
  {
    name: "PHOTOGRAPHY",
    spangram: "APERTURE",
    words: ["LENS", "FOCUS", "FRAME", "SHUTTER", "FILM", "FLASH", "ZOOM", "PRINT", "FILTER", "TRIPOD", "EXPOSE", "PIXEL"],
    insight: "Composing a shot exercises the brain's selective attention, deciding in an instant what to include and what to ignore.",
  },
  {
    name: "ANCIENT ROME",
    spangram: "GLADIATOR",
    words: ["FORUM", "TOGA", "SENATE", "ARENA", "LEGION", "CHARIOT", "VILLA", "CAESAR", "AQUEDUCT", "TEMPLE", "COIN", "SHIELD"],
    insight: "Roman orators built memory palaces, mentally placing facts in familiar rooms — a trick that still outperforms rote learning.",
  },
  {
    name: "SEWING ROOM",
    spangram: "TAILORING",
    words: ["THREAD", "NEEDLE", "SEAM", "CLOTH", "FABRIC", "BUTTON", "ZIPPER", "PLEAT", "STITCH", "CUFF", "HEMS", "DARN"],
    insight: "Threading a needle demands fine motor control and steady focus, briefly recruiting the brain's full attentional spotlight.",
  },
  {
    name: "CORAL REEF",
    spangram: "SNORKELING",
    words: ["CLAM", "ANEMONE", "SPONGE", "POLYP", "WRASSE", "GROUPER", "TANG", "KELP", "DIVER", "LAGOON", "TIDE", "FINS"],
    insight: "Immersing in vivid underwater color and slow movement can shift the brain into a restorative, low-arousal state.",
  },
  {
    name: "WINE MAKING",
    spangram: "VINEYARDS",
    words: ["GRAPE", "CASK", "CORK", "BARREL", "FERMENT", "TANNIN", "VINTAGE", "CELLAR", "HARVEST", "PRESS", "VINE", "OAKS"],
    insight: "Expert tasters build a rich vocabulary of aromas, and naming a smell measurably sharpens the brain's ability to detect it.",
  },
  {
    name: "FIREFIGHTING",
    spangram: "EXTINGUISH",
    words: ["HOSE", "FLAME", "SMOKE", "ALARM", "LADDER", "NOZZLE", "SIREN", "RESCUE", "EMBER", "HELMET", "BLAZE", "HYDRANT"],
    insight: "Under acute danger the amygdala can hijack attention, which is why first responders drill until calm responses become automatic.",
  },
  {
    name: "SPICE MARKET",
    spangram: "CINNAMON",
    words: ["CLOVE", "CUMIN", "SAFFRON", "TURMERIC", "CHILI", "PAPRIKA", "CARDAMOM", "FENNEL", "STAR", "SUMAC", "MACE", "CASSIA"],
    insight: "Curcumin in turmeric is studied for crossing into the brain, where it may curb the inflammation tied to cognitive aging.",
  },
  {
    name: "RAINFOREST",
    spangram: "CANOPIES",
    words: ["VINE", "FERN", "MOSS", "FROG", "TOUCAN", "ORCHID", "LIANA", "HUMID", "MIST", "JAGUAR", "CICADA", "SLOTH"],
    insight: "Rich natural soundscapes like birdsong and rustling leaves help the brain recover focus drained by urban noise.",
  },
  {
    name: "CHESS OPENINGS",
    spangram: "GAMBITS",
    words: ["PAWN", "ROOK", "KING", "FILE", "RANK", "CHECK", "QUEEN", "KNIGHT", "BISHOP", "CASTLE", "MATE", "OPEN"],
    insight: "Chess masters store thousands of board patterns as single chunks, letting them grasp a position at a glance.",
  },
  {
    name: "POTTERY STUDIO",
    spangram: "CERAMICS",
    words: ["CLAY", "KILN", "GLAZE", "WHEEL", "MOLD", "FIRE", "BOWL", "VASE", "POTTER", "SLIP", "BISQUE", "SHAPE"],
    insight: "Shaping clay couples touch with vision, training the brain's sensorimotor loop to predict and correct in real time.",
  },
  {
    name: "TROPICAL STORM",
    spangram: "HURRICANE",
    words: ["WIND", "RAIN", "GUST", "EYE", "SURGE", "FLOOD", "BANDS", "GALE", "FUNNEL", "VORTEX", "SQUALL", "CALM"],
    insight: "Acute stress narrows attention to the threat at hand, a survival reflex that can blur the bigger picture.",
  },
  {
    name: "SUSHI BAR",
    spangram: "WASABIS",
    words: ["RICE", "TUNA", "ROLL", "NORI", "EEL", "CRAB", "GINGER", "SALMON", "TEMPURA", "EDAMAME", "TOFU", "MISO"],
    insight: "Umami, the savory fifth taste, has its own tongue receptors that signal protein-rich food to the hungry brain.",
  },
  {
    name: "CIRCUS SHOW",
    spangram: "ACROBATS",
    words: ["CLOWN", "TENT", "RING", "JUGGLE", "TRAPEZE", "STILTS", "LION", "ACT", "MIME", "UNICYCLE", "BIG", "TOP"],
    insight: "Watching a daring feat fires the brain's mirror neurons, making your own muscles tense as if you were performing it.",
  },
  {
    name: "GREEK ALPHABET",
    spangram: "LETTERING",
    words: ["ALPHA", "BETA", "GAMMA", "DELTA", "OMEGA", "SIGMA", "THETA", "ZETA", "IOTA", "PHI", "PSI", "ETA"],
    insight: "Learning a new symbol set recruits the brain's visual word-form area, rewiring it to read shapes as sounds.",
  },
  {
    name: "BLACKSMITH FORGE",
    spangram: "ANVILING",
    words: ["IRON", "FIRE", "HAMMER", "TONGS", "COAL", "FORGE", "QUENCH", "BLADE", "EMBER", "HEAT", "BELLOWS", "STEEL"],
    insight: "Mastering a craft etches deep procedural memories so movements grow automatic, freeing the mind to focus on nuance.",
  },
  {
    name: "POLAR REGIONS",
    spangram: "ANTARCTIC",
    words: ["ICE", "SNOW", "SEAL", "BEAR", "FROST", "TUNDRA", "WALRUS", "FLOE", "PARKA", "AURORA", "PENGUIN", "WHALE"],
    insight: "Cold-shock exposure spikes noradrenaline, briefly sharpening alertness and mood across the whole brain.",
  },
  {
    name: "MARKET DAY",
    spangram: "BARGAINS",
    words: ["STALL", "COIN", "CART", "PRICE", "TRADE", "VENDOR", "BASKET", "HAGGLE", "CASH", "SCALE", "GOODS", "SELL"],
    insight: "Deciding whether a price is fair lights up the brain's reward and pain circuits, weighing gain against cost in real time.",
  },
  {
    name: "ROBOTICS LAB",
    spangram: "ANDROIDS",
    words: ["GEAR", "MOTOR", "SENSOR", "CIRCUIT", "ARM", "SERVO", "WIRE", "BOLT", "CHIP", "WHEEL", "CODE", "JOINT"],
    insight: "Studying robot control loops mirrors how the brain uses feedback to refine movement, fixing errors before they grow.",
  },
  {
    name: "FENCING MATCH",
    spangram: "RIPOSTES",
    words: ["FOIL", "EPEE", "SABRE", "LUNGE", "PARRY", "GUARD", "MASK", "BLADE", "TOUCH", "FEINT", "PISTE", "BOUT"],
    insight: "Fast dueling sports train the brain to predict an opponent's move milliseconds before it lands, beating conscious reaction.",
  },
  {
    name: "PERFUMERY",
    spangram: "FRAGRANCE",
    words: ["ROSE", "MUSK", "AMBER", "SCENT", "OUD", "NOTE", "SPRAY", "FLORAL", "CITRUS", "BOTTLE", "AROMA", "WOODY"],
    insight: "Scent bypasses the brain's relay station and wires straight to memory and emotion, so a single whiff can unlock the past.",
  },
  {
    name: "LIGHTHOUSE COAST",
    spangram: "BEACONS",
    words: ["LAMP", "ROCK", "WAVE", "CLIFF", "BEAM", "FOG", "KEEPER", "LENS", "SHORE", "TOWER", "SIGNAL", "TIDE"],
    insight: "A flashing landmark grabs attention automatically, exploiting the brain's hardwired bias toward sudden change.",
  },
  {
    name: "ORIGAMI ART",
    spangram: "FOLDINGS",
    words: ["CRANE", "PAPER", "CREASE", "SQUARE", "PLEAT", "BASE", "MODEL", "EDGE", "SWAN", "BOX", "PETAL", "FROG"],
    insight: "Folding precise shapes from memory exercises spatial reasoning, strengthening the brain's mental-rotation skills.",
  },
  {
    name: "JAZZ CLUB",
    spangram: "IMPROVISE",
    words: ["SAX", "BASS", "DRUM", "SOLO", "SWING", "GROOVE", "RIFF", "PIANO", "TRUMPET", "SCALE", "BLUES", "CHORD"],
    insight: "When musicians improvise, the brain's self-monitoring region quiets, letting fluent, spontaneous ideas flow freely.",
  },
  {
    name: "VIKING VOYAGE",
    spangram: "LONGSHIP",
    words: ["OAR", "SAIL", "RUNE", "SHIELD", "FJORD", "RAID", "MAST", "AXE", "HELM", "PROW", "NORSE", "ROWER"],
    insight: "Wayfinding without instruments leaned on the hippocampus, the brain's mapmaker, reading stars, swells and birds.",
  },
  {
    name: "TEA CEREMONY",
    spangram: "STEEPING",
    words: ["LEAF", "POT", "CUP", "BREW", "GREEN", "HERBAL", "KETTLE", "OOLONG", "WHISK", "MATCHA", "SAUCER", "WARM"],
    insight: "Slow, ritual movements engage the brain's calming parasympathetic system, easing the body out of fight-or-flight.",
  },
  {
    name: "MOVIE MAKING",
    spangram: "DIRECTORS",
    words: ["SCENE", "TAKE", "REEL", "ACTOR", "SCRIPT", "EDIT", "CAMERA", "LIGHT", "SET", "CUT", "FRAME", "STUNT"],
    insight: "Film cuts exploit the brain's tendency to stitch separate shots into one seamless story it never actually saw.",
  },
  {
    name: "CAVE EXPLORING",
    spangram: "STALACTITE",
    words: ["CAVE", "DRIP", "ECHO", "DARK", "BAT", "TUNNEL", "CHAMBER", "ROPE", "DAMP", "FLOW", "ROCK", "GUANO"],
    insight: "In total darkness the brain amplifies hearing and touch, reallocating idle visual resources to the senses still in use.",
  },
  {
    name: "SURFING WAVES",
    spangram: "SHOREBREAK",
    words: ["WAVE", "BARREL", "PADDLE", "FOAM", "DUCK", "DROP", "LIPS", "CARVE", "WIPEOUT", "LINEUP", "CREST", "FINS"],
    insight: "Balancing on a moving board sharpens the cerebellum and inner ear, training the brain to predict and correct tilt in real time.",
  },
  {
    name: "MOON PHASES",
    spangram: "WAXINGMOON",
    words: ["FULL", "NEW", "CRESCENT", "GIBBOUS", "WANE", "ORBIT", "TIDE", "GLOW", "HALO", "DARK", "CYCLE", "PHASE"],
    insight: "The brain readily tracks recurring cycles, and lunar rhythms may subtly nudge sleep timing in some people.",
  },
  {
    name: "PIRATE LIFE",
    spangram: "BUCCANEER",
    words: ["SHIP", "GOLD", "MAP", "SWORD", "PLANK", "PARROT", "ANCHOR", "TREASURE", "RUM", "CREW", "MUTINY", "DECK"],
    insight: "Treasure maps work because the brain encodes spatial routes vividly, turning landmarks into easily recalled memory anchors.",
  },
  {
    name: "BICYCLE RIDE",
    spangram: "PEDALLING",
    words: ["WHEEL", "CHAIN", "BRAKE", "GEAR", "SPOKE", "SADDLE", "TIRE", "FRAME", "HELMET", "PUMP", "PATH", "RIDE"],
    insight: "Once learned, cycling becomes procedural memory stored in the cerebellum, which is why you never truly forget how to ride.",
  },
  {
    name: "RAINY DAY",
    spangram: "DOWNPOUR",
    words: ["DRIZZLE", "PUDDLE", "STORM", "CLOUD", "DROP", "SPLASH", "DAMP", "GRAY", "MIST", "POUR", "WET", "SOAK"],
    insight: "The steady patter of rain is a soothing pink-noise pattern that can ease the brain into relaxed, sleepy states.",
  },
  {
    name: "CHEESE BOARD",
    spangram: "FERMENTED",
    words: ["BRIE", "GOUDA", "FETA", "CURD", "RIND", "WEDGE", "CHEDDAR", "WHEY", "AGED", "MOLD", "GRATE", "MELT"],
    insight: "Aged and fermented foods feed gut bacteria that signal the brain through the vagus nerve, subtly shaping mood and appetite.",
  },
  {
    name: "MAGIC SHOW",
    spangram: "ILLUSIONS",
    words: ["TRICK", "CARD", "WAND", "RABBIT", "HAT", "VANISH", "DECK", "CAPE", "SECRET", "PRESTO", "COIN", "STAGE"],
    insight: "Magicians exploit attentional blind spots, steering your spotlight of focus so the brain literally fails to see the move.",
  },
  {
    name: "FROZEN TREATS",
    spangram: "GELATERIA",
    words: ["CONE", "SCOOP", "SORBET", "FUDGE", "SWIRL", "SUNDAE", "SPRINKLE", "LICK", "CHILL", "MELT", "SYRUP", "CREAM"],
    insight: "A cold treat can trigger brain freeze when rapid chilling of the palate sends a misread pain signal to the forehead.",
  },
  {
    name: "TRACK AND FIELD",
    spangram: "MARATHON",
    words: ["SPRINT", "HURDLE", "JAVELIN", "RELAY", "VAULT", "DISCUS", "LANE", "DASH", "SHOTPUT", "LEAP", "BATON", "PACE"],
    insight: "Endurance running floods the brain with endorphins and endocannabinoids, the chemistry behind the fabled runner's high.",
  },
  {
    name: "STARGAZING",
    spangram: "STARLIGHT",
    words: ["STAR", "ORION", "NOVA", "COMET", "NEBULA", "GALAXY", "DIPPER", "GLOW", "DUST", "VOID", "TWINKLE", "POLAR"],
    insight: "Spotting patterns in scattered stars reflects the brain's drive to find shapes, the same instinct that sees faces in clouds.",
  },
  {
    name: "LAUNDRY DAY",
    spangram: "DETERGENT",
    words: ["WASH", "DRYER", "FOLD", "RINSE", "SOAP", "SPIN", "IRON", "LINT", "SOCK", "STAIN", "BLEACH", "HANG"],
    insight: "Mundane repetitive chores free the mind to wander, which is when the brain's default network often sparks fresh ideas.",
  },
  {
    name: "SHOE RACK",
    spangram: "FOOTWEAR",
    words: ["BOOT", "SANDAL", "HEEL", "LACE", "SOLE", "SNEAKER", "LOAFER", "CLOG", "PUMP", "TOE", "SLIPPER", "STRAP"],
    insight: "The brain devotes outsized sensory cortex to the feet, which is why they feel surprisingly ticklish and finely textured.",
  },
  {
    name: "GREEK ISLANDS",
    spangram: "AEGEANSEA",
    words: ["CRETE", "RHODES", "OLIVE", "FERRY", "COVE", "WHITE", "BLUE", "RUINS", "BEACH", "SUNSET", "DOCK", "ISLE"],
    insight: "Vivid travel scenery cements memories strongly, as novelty and emotion together prompt the hippocampus to encode richly.",
  },
  {
    name: "AQUARIUM TANK",
    spangram: "FRESHWATER",
    words: ["GUPPY", "TETRA", "FILTER", "GRAVEL", "PLANT", "PUMP", "GLASS", "SNAIL", "FINS", "BUBBLE", "ANGELFISH", "CORAL"],
    insight: "Watching fish drift in a tank can lower heart rate and blood pressure, easing the brain into a calmer baseline state.",
  },
  {
    name: "SECRET CODES",
    spangram: "ENCRYPTION",
    words: ["CIPHER", "KEY", "DECODE", "SECRET", "MORSE", "GLYPH", "HIDDEN", "VAULT", "LOCK", "SCRAMBLE", "AGENT", "CLUE"],
    insight: "Cracking a code lights up the brain's reward circuit, delivering a satisfying dopamine hit the instant the pattern clicks.",
  },
  {
    name: "WIND POWER",
    spangram: "TURBINES",
    words: ["BLADE", "ROTOR", "GUST", "ENERGY", "GRID", "TOWER", "BREEZE", "GREEN", "POWER", "SPIN", "WATT", "FARM"],
    insight: "The brain itself is a power-hungry organ, drawing roughly twenty watts to keep its eighty-odd billion neurons firing.",
  },
  {
    name: "CHOCOLATE SHOP",
    spangram: "TRUFFLES",
    words: ["COCOA", "FUDGE", "GANACHE", "PRALINE", "DARK", "MILK", "BAR", "MELT", "BEAN", "NIBS", "SWEET", "CARAMEL"],
    insight: "Chocolate contains compounds that gently lift mood, partly by nudging the brain's serotonin and dopamine systems.",
  },
  {
    name: "GHOST STORY",
    spangram: "HAUNTING",
    words: ["GHOST", "SPOOK", "CHILL", "MANOR", "CREAK", "SHADOW", "SPECTER", "MOAN", "EERIE", "PHANTOM", "DREAD", "FOG"],
    insight: "A good scare hijacks the amygdala, firing the body's alarm before the slower thinking brain confirms there is no danger.",
  },
  {
    name: "KITE FLYING",
    spangram: "TAILWIND",
    words: ["STRING", "BREEZE", "SOAR", "SPOOL", "DIVE", "GUST", "FRAME", "TAIL", "LOOP", "DRIFT", "FLY", "REEL"],
    insight: "Tracking a darting kite across the sky trains smooth-pursuit eye movements, a finely tuned visual skill the brain refines with practice.",
  },
];
