import type { ThemeEntry } from "./engine";

/**
 * The Mind Strands theme bank. Each entry is a category with a spangram (which
 * spans the grid) and a generous pool of on-theme words. The generator selects
 * a subset of the pool whose lengths plus the spangram total exactly 48 letters
 * (the 6×8 grid), then packs them. Pools are deliberately oversized with varied
 * lengths so a 48-letter subset (4–8 words) always exists for the packer.
 *
 * Words are uppercase A–Z only. Every entry is validated in engine.test.ts.
 */
export const BANK: ThemeEntry[] = [
  {
    name: "BRAIN ANATOMY",
    spangram: "CEREBRUM",
    words: ["CORTEX", "NEURON", "SYNAPSE", "AXON", "MEMORY", "DENDRITE", "LOBE", "STEM", "THALAMUS", "PONS", "GLIA", "NERVE"],
    insight: "The cerebrum is the brain's largest region — its folded cortex handles thought, language and voluntary action across two mirror-image hemispheres.",
  },
  {
    name: "MEMORY TRICKS",
    spangram: "MNEMONICS",
    words: ["RECALL", "CHUNK", "REPEAT", "SPACING", "ANCHOR", "REVIEW", "CUE", "PEG", "STORY", "IMAGE", "LINK", "RHYME"],
    insight: "Spacing your study sessions and chunking information into meaningful groups dramatically strengthen long-term memory storage.",
  },
  {
    name: "HOW WE LEARN",
    spangram: "PLASTICITY",
    words: ["PRACTICE", "REPEAT", "RECALL", "FOCUS", "ERROR", "HABIT", "SKILL", "DRILL", "STUDY", "EFFORT", "RETRY", "GROW"],
    insight: "Your brain physically rewires itself as you learn — new neural pathways form with practice, even well into adulthood.",
  },
  {
    name: "STAYING FOCUSED",
    spangram: "ATTENTION",
    words: ["FOCUS", "ALERT", "FILTER", "IGNORE", "TARGET", "SCAN", "TRACK", "NOTICE", "AWARE", "ZONE", "GAZE", "WATCH"],
    insight: "Attention works like a spotlight: focusing on one thing dims everything else, which is why multitasking quietly drains accuracy.",
  },
  {
    name: "FEELING IT",
    spangram: "AMYGDALA",
    words: ["FEAR", "JOY", "ANGER", "TRUST", "MOOD", "STRESS", "CALM", "PANIC", "RELIEF", "DREAD", "WORRY", "PRIDE"],
    insight: "Your amygdala can flag a threat in milliseconds, often firing before your conscious mind has even registered what happened.",
  },
  {
    name: "SLEEP CYCLE",
    spangram: "CIRCADIAN",
    words: ["DREAM", "REST", "NAP", "WAKE", "NIGHT", "MELATONIN", "DEEP", "SNORE", "DROWSY", "YAWN", "DOZE", "PILLOW"],
    insight: "Deep sleep clears metabolic waste from the brain and consolidates the day's memories into durable long-term storage.",
  },
  {
    name: "THE SENSES",
    spangram: "PERCEPTION",
    words: ["SIGHT", "SOUND", "TASTE", "SMELL", "TOUCH", "SENSE", "HEAR", "FEEL", "ODOR", "VISION", "FLAVOR", "NOISE"],
    insight: "Perception is your brain's best guess — it constantly predicts the world and corrects itself against incoming sensory data.",
  },
  {
    name: "BIG IDEAS",
    spangram: "CREATIVITY",
    words: ["IDEA", "MUSE", "SPARK", "DREAM", "DESIGN", "INVENT", "VISION", "CRAFT", "NOVEL", "FLAIR", "ORIGINAL", "IMAGINE"],
    insight: "Creative insight often arrives during mind-wandering, when the brain's default-mode network links distant ideas in fresh ways.",
  },
  {
    name: "SOLAR SYSTEM",
    spangram: "PLANETARY",
    words: ["MARS", "VENUS", "EARTH", "SATURN", "COMET", "MOON", "ORBIT", "PLUTO", "SUN", "URANUS", "NEPTUNE", "METEOR"],
    insight: "The brain builds spatial maps using grid cells — the same machinery that helps you imagine the layout of the solar system.",
  },
  {
    name: "WEATHER WATCH",
    spangram: "ATMOSPHERE",
    words: ["RAIN", "STORM", "CLOUD", "WIND", "SNOW", "FROST", "THUNDER", "MIST", "HAIL", "SLEET", "BREEZE", "GALE"],
    insight: "Predicting weather, like predicting anything, taps the brain's prefrontal cortex, which models likely futures from past patterns.",
  },
  {
    name: "OCEAN LIFE",
    spangram: "UNDERWATER",
    words: ["CORAL", "SHARK", "WHALE", "SQUID", "REEF", "TIDE", "WAVE", "EEL", "CRAB", "OCTOPUS", "SEAL", "RAY"],
    insight: "Octopuses have neurons distributed through their arms, a strikingly different design from the centralized vertebrate brain.",
  },
  {
    name: "IN THE GARDEN",
    spangram: "BOTANICAL",
    words: ["ROSE", "TULIP", "SEED", "LEAF", "PETAL", "STEM", "ROOT", "BLOOM", "SOIL", "SPROUT", "VINE", "BUD"],
    insight: "Spending time around greenery measurably lowers stress hormones and restores depleted attention in the prefrontal cortex.",
  },
  {
    name: "KITCHEN SPICES",
    spangram: "SEASONING",
    words: ["CUMIN", "BASIL", "THYME", "CLOVE", "GINGER", "MINT", "SAGE", "CHILI", "PEPPER", "NUTMEG", "DILL", "ANISE"],
    insight: "Smell links directly to memory: aromas route through the olfactory bulb straight to the hippocampus, evoking vivid recall.",
  },
  {
    name: "FRESH FRUIT",
    spangram: "ORCHARDS",
    words: ["APPLE", "MANGO", "GRAPE", "PEACH", "LEMON", "PLUM", "PEAR", "BERRY", "CHERRY", "MELON", "KIWI", "FIG"],
    insight: "Antioxidant-rich berries support memory; flavonoids appear to improve blood flow to memory-critical brain regions.",
  },
  {
    name: "MUSIC THEORY",
    spangram: "HARMONIES",
    words: ["TEMPO", "CHORD", "SCALE", "NOTE", "BEAT", "PITCH", "TUNE", "REST", "MELODY", "RHYTHM", "KEY", "OCTAVE"],
    insight: "Learning music engages motor, auditory and emotional circuits at once, building unusually dense cross-brain connections.",
  },
  {
    name: "ART STUDIO",
    spangram: "PALETTES",
    words: ["BRUSH", "CANVAS", "PAINT", "EASEL", "SHADE", "TONE", "INK", "FRAME", "SKETCH", "COLOR", "PASTEL", "CHALK"],
    insight: "Viewing art activates the brain's reward system, releasing dopamine much as food or social connection does.",
  },
  {
    name: "WORLD CITIES",
    spangram: "METROPOLIS",
    words: ["PARIS", "TOKYO", "CAIRO", "LIMA", "ROME", "OSLO", "DELHI", "SEOUL", "MADRID", "BERLIN", "DUBAI", "MILAN"],
    insight: "London taxi drivers grow a larger hippocampus from memorizing the city — a vivid example of adult neuroplasticity.",
  },
  {
    name: "MOUNTAIN RANGE",
    spangram: "ALTITUDES",
    words: ["PEAK", "RIDGE", "CLIFF", "SLOPE", "SUMMIT", "TRAIL", "ROCK", "VALLEY", "CRAG", "GORGE", "FACE", "SCREE"],
    insight: "At high altitude the brain adapts to thinner air by boosting blood flow and red-cell production over several days.",
  },
  {
    name: "RIVER JOURNEY",
    spangram: "TRIBUTARY",
    words: ["DELTA", "BANK", "FLOW", "RAPID", "BEND", "MOUTH", "SOURCE", "STREAM", "CURRENT", "EDDY", "FORD", "POOL"],
    insight: "The brain prefers to conserve energy, often choosing the cognitive path of least resistance — much like water finding its course.",
  },
  {
    name: "DESERT LANDS",
    spangram: "ARIDITY",
    words: ["DUNE", "OASIS", "CACTUS", "SAND", "CAMEL", "MIRAGE", "HEAT", "DRY", "DUST", "SCRUB", "BARREN", "WADI"],
    insight: "A mirage is your visual system misreading bent light — proof that perception is interpretation, not raw recording.",
  },
  {
    name: "BIRD WATCHING",
    spangram: "PLUMAGE",
    words: ["ROBIN", "FINCH", "HAWK", "WREN", "CROW", "DOVE", "OWL", "HERON", "EAGLE", "SPARROW", "STORK", "JAY"],
    insight: "Some birds shrink and regrow brain regions seasonally to learn new songs — a dramatic form of neural plasticity.",
  },
  {
    name: "JUNGLE CREATURES",
    spangram: "PRIMATES",
    words: ["TIGER", "SLOTH", "GECKO", "TAPIR", "MACAW", "FROG", "ANT", "JAGUAR", "MONKEY", "PARROT", "SNAKE", "LEMUR"],
    insight: "Primate brains devote enormous resources to vision and social tracking, which helped our own intelligence evolve.",
  },
  {
    name: "WINTER SPORTS",
    spangram: "TOBOGGAN",
    words: ["SKI", "SKATE", "SLED", "CURL", "LUGE", "JUMP", "GLIDE", "CARVE", "HOCKEY", "SLALOM", "BOARD", "RINK"],
    insight: "Balancing on skis trains the cerebellum, the brain's coordination center that smooths and fine-tunes every movement.",
  },
  {
    name: "BALL GAMES",
    spangram: "ATHLETICS",
    words: ["GOAL", "SERVE", "PITCH", "DRIBBLE", "PASS", "KICK", "SHOOT", "DUNK", "SCORE", "VOLLEY", "TACKLE", "SPIKE"],
    insight: "Expert athletes show faster neural processing in motion-prediction areas, reacting before slower conscious thought kicks in.",
  },
  {
    name: "BOARD GAMES",
    spangram: "STRATEGY",
    words: ["CHESS", "DICE", "PAWN", "MOVE", "ROOK", "TILE", "TURN", "PIECE", "BOARD", "TOKEN", "KNIGHT", "BISHOP"],
    insight: "Strategic games strengthen working memory and planning by forcing the prefrontal cortex to simulate moves ahead.",
  },
  {
    name: "CARD PLAY",
    spangram: "SHUFFLES",
    words: ["ACE", "KING", "QUEEN", "JACK", "DEAL", "BLUFF", "HAND", "SUIT", "TRUMP", "SPADE", "HEART", "CLUB"],
    insight: "Bluffing recruits theory-of-mind circuits as you model what your opponent believes you believe.",
  },
  {
    name: "TASTY BREAKFAST",
    spangram: "PANCAKES",
    words: ["TOAST", "EGGS", "BACON", "JAM", "OATS", "JUICE", "WAFFLE", "CEREAL", "BAGEL", "MUFFIN", "HONEY", "BUTTER"],
    insight: "Glucose from breakfast fuels neurons directly; the brain burns about a fifth of your daily energy despite its small size.",
  },
  {
    name: "BAKING DAY",
    spangram: "KNEADING",
    words: ["FLOUR", "DOUGH", "YEAST", "SUGAR", "OVEN", "LOAF", "CRUST", "WHISK", "BATTER", "ROLL", "PROOF", "GLAZE"],
    insight: "Repetitive, hands-on tasks like kneading can induce a calming flow state that quiets the brain's worry network.",
  },
  {
    name: "COFFEE BREAK",
    spangram: "CAFFEINE",
    words: ["BEAN", "BREW", "MUG", "FOAM", "ROAST", "DRIP", "LATTE", "MOCHA", "CREAM", "GRIND", "CUP", "STEAM"],
    insight: "Caffeine blocks adenosine, the molecule that builds up sleep pressure, temporarily masking the brain's sense of fatigue.",
  },
  {
    name: "TOOLBOX",
    spangram: "HARDWARE",
    words: ["DRILL", "SAW", "NAIL", "BOLT", "WRENCH", "HAMMER", "VISE", "FILE", "PLIERS", "SCREW", "CHISEL", "CLAMP"],
    insight: "Tool use lit up planning and motor circuits in early humans, a feedback loop that helped push brain size upward.",
  },
  {
    name: "CLOTHING",
    spangram: "WARDROBE",
    words: ["SHIRT", "JEANS", "SCARF", "GLOVE", "BOOT", "COAT", "SOCK", "HAT", "DRESS", "JACKET", "BELT", "SWEATER"],
    insight: "Recognizing a familiar outfit relies on the fusiform area, the same region that specializes in spotting faces.",
  },
  {
    name: "ON THE FARM",
    spangram: "LIVESTOCK",
    words: ["COW", "PIG", "HEN", "GOAT", "SHEEP", "BARN", "PLOW", "FIELD", "TRACTOR", "HORSE", "FENCE", "SILO"],
    insight: "Animals navigating familiar pastures use the same hippocampal place cells that build your own mental maps.",
  },
  {
    name: "DINOSAUR ERA",
    spangram: "FOSSILIZED",
    words: ["TREX", "RAPTOR", "BONE", "SCALE", "CLAW", "EGG", "HORN", "TAIL", "SPIKE", "JAW", "STEGO", "REPTILE"],
    insight: "Endocasts of dinosaur skulls let scientists reconstruct ancient brains and infer surprising senses and behaviors.",
  },
  {
    name: "ROCK TYPES",
    spangram: "MINERALS",
    words: ["GRANITE", "SLATE", "QUARTZ", "CHALK", "BASALT", "GEM", "ORE", "FLINT", "SHALE", "MARBLE", "CLAY", "PUMICE"],
    insight: "Categorizing objects like rocks engages the brain's semantic networks, which file knowledge by shared features.",
  },
  {
    name: "CHEMISTRY LAB",
    spangram: "MOLECULES",
    words: ["ATOM", "ACID", "BASE", "IONS", "BOND", "GAS", "SALT", "MIX", "FLASK", "BEAKER", "VAPOR", "SOLVENT"],
    insight: "Neurotransmitters are simple molecules, yet tiny shifts in their balance dramatically alter mood and cognition.",
  },
  {
    name: "MATH WORLD",
    spangram: "EQUATIONS",
    words: ["SUM", "PRIME", "ANGLE", "GRAPH", "RATIO", "PROOF", "LOGIC", "DIGIT", "FACTOR", "VECTOR", "SET", "POWER"],
    insight: "Doing math activates the intraparietal sulcus, a region that represents quantity even in pre-verbal infants.",
  },
  {
    name: "COMPUTER PARTS",
    spangram: "PROCESSOR",
    words: ["CHIP", "RAM", "DISK", "CABLE", "MOUSE", "SCREEN", "PORT", "DRIVE", "BOARD", "FAN", "MEMORY", "CACHE"],
    insight: "The brain is wildly more energy-efficient than any computer, running on roughly the wattage of a dim light bulb.",
  },
  {
    name: "SPACE TRAVEL",
    spangram: "ASTRONAUT",
    words: ["ROCKET", "LAUNCH", "ORBIT", "CREW", "SUIT", "MOON", "STAR", "PROBE", "SHUTTLE", "BOOSTER", "PAD", "HATCH"],
    insight: "In weightlessness the brain quickly recalibrates balance, remapping which signals to trust from the inner ear and eyes.",
  },
  {
    name: "ANCIENT EGYPT",
    spangram: "PYRAMIDS",
    words: ["PHARAOH", "SPHINX", "NILE", "TOMB", "SCROLL", "MUMMY", "GOLD", "SAND", "TEMPLE", "OBELISK", "REED", "GLYPH"],
    insight: "Reading hieroglyphs, like any script, recruits a brain region that learning literally repurposes from object recognition.",
  },
  {
    name: "MYTHOLOGY",
    spangram: "LEGENDARY",
    words: ["TITAN", "HYDRA", "OMEN", "ORACLE", "QUEST", "HERO", "MUSE", "FATE", "NYMPH", "PHOENIX", "GOD", "BEAST"],
    insight: "Stories stick because the brain encodes narrative far more readily than disconnected facts, linking cause to consequence.",
  },
  {
    name: "CASTLE LIFE",
    spangram: "MEDIEVAL",
    words: ["KNIGHT", "MOAT", "TOWER", "SWORD", "CROWN", "GATE", "ARMOR", "KING", "QUEEN", "SHIELD", "KEEP", "LANCE"],
    insight: "Vivid imagery, like a fortress, makes information memorable — the basis of the ancient memory-palace technique.",
  },
  {
    name: "DETECTIVE WORK",
    spangram: "MYSTERIES",
    words: ["CLUE", "ALIBI", "MOTIVE", "SUSPECT", "PROOF", "CASE", "TRACE", "SOLVE", "WITNESS", "HUNCH", "LEAD", "CRIME"],
    insight: "Solving puzzles rewards the brain with a dopamine 'aha' hit, reinforcing the persistence that cracked the problem.",
  },
  {
    name: "EMOTIONS",
    spangram: "FEELINGS",
    words: ["HAPPY", "SAD", "ANGRY", "PROUD", "SHY", "BORED", "GLAD", "TENSE", "CALM", "EAGER", "JOY", "GRIEF"],
    insight: "Naming an emotion calms the amygdala — putting feelings into words measurably reduces their intensity.",
  },
  {
    name: "BODY SYSTEMS",
    spangram: "CIRCULATION",
    words: ["HEART", "LUNG", "VEIN", "NERVE", "BONE", "MUSCLE", "SKIN", "GLAND", "ARTERY", "KIDNEY", "LIVER", "SPINE"],
    insight: "Your brain claims about 20 percent of your blood flow and oxygen, far out of proportion to its modest weight.",
  },
  {
    name: "FIVE TASTES",
    spangram: "FLAVORFUL",
    words: ["SWEET", "SOUR", "SALTY", "BITTER", "SPICY", "TANGY", "RICH", "MILD", "UMAMI", "ZESTY", "SHARP", "SMOKY"],
    insight: "Flavor is multisensory — most of what you 'taste' is actually smell, which is why food seems flat with a head cold.",
  },
  {
    name: "WEATHER MOODS",
    spangram: "SUNSHINE",
    words: ["BREEZE", "DRIZZLE", "GUST", "HAZE", "CHILL", "WARM", "DAMP", "CLEAR", "MUGGY", "CRISP", "BALMY", "FOGGY"],
    insight: "Bright light boosts serotonin, which is partly why sunny days tend to lift mood and sharpen alertness.",
  },
  {
    name: "TIME WORDS",
    spangram: "CALENDAR",
    words: ["HOUR", "WEEK", "MONTH", "YEAR", "DAWN", "DUSK", "NOON", "ERA", "MINUTE", "SECOND", "DECADE", "EPOCH"],
    insight: "The brain has no single clock; it stitches together overlapping rhythms to build your fluid sense of passing time.",
  },
  {
    name: "COLORS",
    spangram: "SPECTRUM",
    words: ["RED", "BLUE", "GREEN", "AMBER", "TEAL", "PINK", "GOLD", "GRAY", "VIOLET", "INDIGO", "OLIVE", "CORAL"],
    insight: "Color isn't in the world but in the head: your brain constructs hue from how cone cells compare wavelengths of light.",
  },
  {
    name: "SHAPES",
    spangram: "GEOMETRY",
    words: ["CIRCLE", "SQUARE", "OVAL", "CUBE", "CONE", "STAR", "ARC", "PRISM", "SPHERE", "PYRAMID", "RHOMBUS", "DISK"],
    insight: "The brain spots shapes by detecting edges and angles in the visual cortex before assembling them into whole objects.",
  },
  {
    name: "READING TIME",
    spangram: "LIBRARY",
    words: ["NOVEL", "PAGE", "CHAPTER", "PLOT", "PROSE", "INDEX", "STORY", "VERSE", "AUTHOR", "SPINE", "TITLE", "GENRE"],
    insight: "Deep reading builds dense connections between language and imagination centers, strengthening focus over time.",
  },
  {
    name: "WRITING TOOLS",
    spangram: "PENMANSHIP",
    words: ["PEN", "INK", "QUILL", "PAPER", "DRAFT", "EDIT", "WORD", "NOTE", "PENCIL", "ERASER", "MARGIN", "TYPE"],
    insight: "Writing by hand activates motor and memory circuits more richly than typing, which can deepen learning.",
  },
  {
    name: "TRANSPORT",
    spangram: "VEHICLES",
    words: ["TRAIN", "BUS", "TRAM", "FERRY", "BIKE", "CAR", "TAXI", "VAN", "TRUCK", "SCOOTER", "WAGON", "BOAT"],
    insight: "Navigating routes exercises the hippocampus; over-relying on GPS may quietly weaken this natural mapping ability.",
  },
  {
    name: "AIR TRAVEL",
    spangram: "AIRCRAFT",
    words: ["JET", "WING", "PILOT", "RUNWAY", "CABIN", "GATE", "FLIGHT", "TAIL", "ENGINE", "TICKET", "RADAR", "AISLE"],
    insight: "Jet lag is your circadian clock lagging behind the new time zone, slowly resyncing to the local light schedule.",
  },
  {
    name: "INSECT WORLD",
    spangram: "ANTENNAE",
    words: ["BEE", "ANT", "MOTH", "WASP", "BEETLE", "FLY", "APHID", "GNAT", "CRICKET", "LOCUST", "MANTIS", "WEEVIL"],
    insight: "Honeybee brains, smaller than a grass seed, still master counting, navigation and symbolic learning.",
  },
  {
    name: "PET ANIMALS",
    spangram: "COMPANION",
    words: ["DOG", "CAT", "FISH", "BIRD", "RABBIT", "MOUSE", "FERRET", "GECKO", "HAMSTER", "PARROT", "PUPPY", "KITTEN"],
    insight: "Petting an animal lowers cortisol and raises oxytocin, easing the brain's stress response within minutes.",
  },
  {
    name: "TREE SPECIES",
    spangram: "FORESTRY",
    words: ["OAK", "PINE", "MAPLE", "BIRCH", "CEDAR", "ELM", "ASH", "WILLOW", "SPRUCE", "POPLAR", "BEECH", "ASPEN"],
    insight: "Forest walks reduce mental fatigue, restoring the directed attention that city environments steadily drain.",
  },
  {
    name: "GEMSTONES",
    spangram: "JEWELRY",
    words: ["RUBY", "OPAL", "PEARL", "JADE", "TOPAZ", "AMBER", "ONYX", "GARNET", "EMERALD", "AGATE", "BERYL", "ZIRCON"],
    insight: "Spotting a sparkle grabs attention automatically — the brain is wired to notice shine, an ancient cue for water.",
  },
  {
    name: "WATER FORMS",
    spangram: "HYDRATION",
    words: ["LAKE", "POND", "RIVER", "WAVE", "ICE", "STEAM", "MIST", "RAIN", "BROOK", "OCEAN", "PUDDLE", "DROP"],
    insight: "Even mild dehydration impairs concentration and short-term memory, since neurons depend on steady fluid balance.",
  },
  {
    name: "VOLCANO",
    spangram: "ERUPTION",
    words: ["LAVA", "ASH", "MAGMA", "CRATER", "VENT", "ROCK", "PLUME", "DOME", "CALDERA", "FLOW", "STEAM", "EMBER"],
    insight: "A sudden eruption triggers the brain's fast threat pathway, flooding the body with adrenaline before you can think.",
  },
  {
    name: "PUZZLE TYPES",
    spangram: "CROSSWORD",
    words: ["MAZE", "SUDOKU", "RIDDLE", "CIPHER", "LOGIC", "JIGSAW", "CODE", "CLUE", "ANAGRAM", "REBUS", "GRID", "QUIZ"],
    insight: "Varied puzzling keeps multiple cognitive domains active, which research links to sharper aging minds.",
  },
  {
    name: "DANCE STYLES",
    spangram: "BALLROOM",
    words: ["WALTZ", "TANGO", "SALSA", "SWING", "STEP", "SPIN", "LEAP", "TWIRL", "RUMBA", "FOXTROT", "JIVE", "SWAY"],
    insight: "Learning dance routines challenges memory and coordination together, a combo linked to better brain health with age.",
  },
  {
    name: "WEATHER SKY",
    spangram: "RAINBOWS",
    words: ["CLOUD", "SUN", "STORM", "BOLT", "HALO", "SLEET", "GUST", "DEW", "AURORA", "COMET", "MOON", "STAR"],
    insight: "A rainbow exists only from your vantage point — your brain assembles it from light bending through countless droplets.",
  },
  {
    name: "FAIRY TALE",
    spangram: "ENCHANTED",
    words: ["WITCH", "SPELL", "CROWN", "DRAGON", "WAND", "OGRE", "GOLD", "CURSE", "POTION", "GIANT", "TROLL", "FAIRY"],
    insight: "Imagining magical scenes lights up the same visual regions as actually seeing, blurring the line between sight and thought.",
  },
];
